import{useEffect,useRef,useState}from'react';import{Plus,Copy,ArrowUp,ArrowDown,Trash2,Undo2,Eye,Edit3,Download}from'lucide-react';import type{EditorProps}from'../types';import{downloadFile}from'../io';
export default function NotebookEditor({file,onChange}:EditorProps){const pages=file.data.pages?.length?file.data.pages:[{id:'first',title:'Untitled page',text:''}];const[active,setActive]=useState(pages[0]?.id),[query,setQuery]=useState(''),[preview,setPreview]=useState(false),[notice,setNotice]=useState(''),[tick,setTick]=useState(0);const past=useRef<any[]>([]),last=useRef(JSON.stringify(file.data));const page=pages.find((p:any)=>p.id===active)||pages[0];
 useEffect(()=>{const current=JSON.stringify(file.data);if(current!==last.current){past.current=[];setTick(t=>t+1);}last.current=current;},[file.data]);
 function change(next:any[]){past.current.push(structuredClone(file.data));if(past.current.length>60)past.current.shift();last.current=JSON.stringify({...file.data,pages:next});onChange({...file.data,pages:next});setTick(t=>t+1);}
 function update(patch:any){change(pages.map((p:any)=>p.id===page.id?{...p,...patch}:p));}function move(delta:number){const next=[...pages],i=next.findIndex(p=>p.id===page.id),j=i+delta;if(j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];change(next);}function undo(){const prior=past.current.pop();if(prior){last.current=JSON.stringify(prior);onChange(prior);setTick(t=>t+1);}}
 async function exportNotes(){try{if(window.office){const result=await window.office.convertExport(file,'md');setNotice(result.cancelled?'Export cancelled.':result.warnings?.join(' ')||'Notebook exported.');}else await downloadFile(file.name,pages.map((p:any)=>'# '+p.title+'\n\n'+p.text).join('\n\n'),'md');}catch(e:any){setNotice(e.message);}}
 if(!page)return <p role="alert">This notebook has no pages.</p>;
 return <div className="notebook notebook-enhanced"><aside><div className="section-label">PAGES<button aria-label="Add page" onClick={()=>{const id=crypto.randomUUID();change([...pages,{id,title:'Untitled page',text:''}]);setActive(id);}}><Plus size={16}/></button></div><input className="note-page-search" aria-label="Search notebook pages" placeholder="Find a page…" value={query} onChange={e=>setQuery(e.target.value)}/>{pages.filter((p:any)=>(p.title+' '+p.text).toLowerCase().includes(query.toLowerCase())).map((p:any)=><button key={p.id} className={p.id===page.id?'selected':''} onClick={()=>setActive(p.id)}>{p.title||'Untitled page'}</button>)}<p className="note-count">{pages.length} pages</p></aside><article><div className="note-tools"><button aria-label="Undo notebook edit" disabled={!past.current.length} onClick={undo}><Undo2 size={16}/></button><button aria-label="Duplicate page" onClick={()=>{const id=crypto.randomUUID();change([...pages,{...structuredClone(page),id,title:page.title+' (copy)'}]);setActive(id);}}><Copy size={16}/></button><button aria-label="Move page up" disabled={pages[0].id===page.id} onClick={()=>move(-1)}><ArrowUp size={16}/></button><button aria-label="Move page down" disabled={pages.at(-1).id===page.id} onClick={()=>move(1)}><ArrowDown size={16}/></button><button aria-label="Delete page" disabled={pages.length<2} onClick={()=>{const next=pages.filter((p:any)=>p.id!==page.id);change(next);setActive(next[0].id);}}><Trash2 size={16}/></button><button onClick={()=>setPreview(!preview)}>{preview?<Edit3 size={16}/>:<Eye size={16}/>} {preview?'Edit':'Preview'}</button><button onClick={()=>void exportNotes()}><Download size={16}/>Export notebook</button></div><input aria-label="Page title" className="note-title" value={page.title} onChange={e=>update({title:e.target.value})}/>{preview?<div className="note-preview" aria-label="Note preview">{page.text.split('\n').map((line:string,i:number)=>line.startsWith('### ')?<h3 key={i}>{line.slice(4)}</h3>:line.startsWith('## ')?<h2 key={i}>{line.slice(3)}</h2>:line.startsWith('# ')?<h1 key={i}>{line.slice(2)}</h1>:/^[-*] /.test(line)?<p key={i}>• {line.slice(2)}</p>:<p key={i}>{line||'\u00a0'}</p>)}</div>:<textarea aria-label="Notes" placeholder="A place for your next idea..." value={page.text} onChange={e=>update({text:e.target.value})}/>}<footer>{page.text.trim().split(/\s+/).filter(Boolean).length} words · {page.text.length} characters{notice&&<span role="status"> · {notice}</span>}</footer></article></div>;
}
