import {useEffect,useRef,useState} from 'react';
import {Plus,Copy,Trash2,ChevronUp,ChevronDown,Play,Download,ImagePlus,ArrowLeft,ArrowRight,X,Upload,Undo2,Redo2} from 'lucide-react';
import type {EditorProps} from '../types';
import {downloadFile} from '../io';
import './PresentationEditor.css';

type Slide={id:string;title:string;body:string;right:string;notes:string;layout:'title'|'content'|'columns';image?:string;background?:string};
type Deck={slides:Slide[];theme:string};
const themes=[{id:'editorial',name:'Editorial',bg:'#F5F1E8',fg:'#23372F',accent:'#BD633F'},{id:'cobalt',name:'Cobalt',bg:'#1742CB',fg:'#FFFFFF',accent:'#BDED83'},{id:'midnight',name:'Midnight',bg:'#192821',fg:'#F7F4EA',accent:'#C2DB96'},{id:'paper',name:'Paper',bg:'#FFFFFF',fg:'#252C39',accent:'#276F57'}];
const fresh=():Slide=>({id:crypto.randomUUID(),title:'An idea worth sharing',body:'Add your key message here.\nKeep it clear. Make it memorable.',right:'A second perspective',notes:'',layout:'content'});
const initial=():Deck=>({theme:'editorial',slides:[{...fresh(),title:'Good things\nstart with an idea.',body:'A little clarity. A new perspective.\nYour next chapter starts here.',layout:'title'}]});
export default function PresentationEditor({file,onChange}:EditorProps){
 const fallback=useRef(initial());const data:Deck=Array.isArray(file.data?.slides)&&file.data.slides.length?file.data:fallback.current;
 const slides=data.slides;const [selected,setSelected]=useState(0);const [present,setPresent]=useState(false);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const imageInput=useRef<HTMLInputElement>(null);const backupInput=useRef<HTMLInputElement>(null);const stage=useRef<HTMLDivElement>(null);
 const index=Math.min(selected,slides.length-1);const slide=slides[index];const theme=themes.find(t=>t.id===data.theme)||themes[0];
 const history=useRef<{past:{deck:Deck;selected:number}[];future:{deck:Deck;selected:number}[]}>({past:[],future:[]});
 const expected=useRef({id:file.id,json:JSON.stringify(data)});const [,refreshHistory]=useState(0);
 // A different deck from disk is an external edit, never an undo target.
 useEffect(()=>{const json=JSON.stringify(data);if(expected.current.id!==file.id||expected.current.json!==json){history.current={past:[],future:[]};expected.current={id:file.id,json};refreshHistory(n=>n+1);}},[data,file.id]);
 const publish=(next:Deck)=>{expected.current={id:file.id,json:JSON.stringify(next)};onChange(next);refreshHistory(n=>n+1);};
 const save=(next:Deck)=>{if(JSON.stringify(next)===JSON.stringify(data))return;history.current.past=[...history.current.past,{deck:data,selected:index}].slice(-100);history.current.future=[];publish(next);};
 const travel=(redo=false)=>{const from=redo?history.current.future:history.current.past;const snapshot=from.pop();if(!snapshot)return;const to=redo?history.current.past:history.current.future;to.push({deck:data,selected:index});if(to.length>100)to.shift();setSelected(snapshot.selected);publish(snapshot.deck);};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(present||!(e.ctrlKey||e.metaKey)||e.altKey)return;const target=e.target as HTMLElement;if(target?.closest?.('.editor-header'))return;const k=e.key.toLowerCase();if(k==='z'||k==='y'){e.preventDefault();travel(k==='y'||e.shiftKey);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});const patch=(values:Partial<Slide>)=>save({...data,slides:slides.map((s,i)=>i===index?{...s,...values}:s)});
 useEffect(()=>{setSelected(0);setPresent(false)},[file.id]);
 useEffect(()=>{if(!present)return;const handler=(event:KeyboardEvent)=>{if(['ArrowRight','ArrowDown',' ','PageDown'].includes(event.key)){event.preventDefault();setSelected(n=>Math.min(n+1,slides.length-1))}if(['ArrowLeft','ArrowUp','PageUp'].includes(event.key)){event.preventDefault();setSelected(n=>Math.max(0,n-1))}if(event.key==='Escape')setPresent(false)};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[present,slides.length]);
 useEffect(()=>{const leave=()=>{if(!document.fullscreenElement)setPresent(false)};document.addEventListener('fullscreenchange',leave);return()=>document.removeEventListener('fullscreenchange',leave)},[]);
 const add=()=>{const next=[...slides];next.splice(index+1,0,fresh());save({...data,slides:next});setSelected(index+1)};
 const duplicate=()=>{const next=[...slides];next.splice(index+1,0,{...slide,id:crypto.randomUUID()});save({...data,slides:next});setSelected(index+1)};
 const remove=()=>{if(slides.length===1)return;save({...data,slides:slides.filter((_,i)=>i!==index)});setSelected(Math.max(0,index-1))};
 const move=(delta:number)=>{const target=index+delta;if(target<0||target>=slides.length)return;const next=[...slides];[next[index],next[target]]=[next[target],next[index]];save({...data,slides:next});setSelected(target)};
 const start=async()=>{setPresent(true);try{await stage.current?.requestFullscreen()}catch{/* Presentation also works in a full-window overlay. */}};
 const end=()=>{setPresent(false);if(document.fullscreenElement)void document.exitFullscreen()};
 const exportPptx=async()=>{setBusy(true);setStatus('');try{const {default:PptxGenJS}=await import('pptxgenjs');const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='Workspace';pptx.subject=file.name;pptx.title=file.name;
 for(const item of slides){const page=pptx.addSlide();page.background={color:(item.background||theme.bg).slice(1)};const color=theme.fg.slice(1);const titleLayout=item.layout==='title';page.addText(item.title,{x:.75,y:titleLayout?1.65:.65,w:item.image?7.2:11.8,h:titleLayout?2.1:1.2,fontFace:'Aptos Display',fontSize:titleLayout?42:30,bold:true,color,breakLine:false,margin:0,fit:'shrink'});page.addText(item.body||'',{x:.8,y:titleLayout?4.15:2.15,w:item.image||item.layout==='columns'?5.7:11.6,h:2.8,fontFace:'Aptos',fontSize:22,color,margin:0,fit:'shrink',paraSpaceAfter:12});if(item.layout==='columns'&&!item.image)page.addText(item.right||'',{x:7,y:2.15,w:5.5,h:3.5,fontFace:'Aptos',fontSize:22,color,margin:0,fit:'shrink'});if(item.image)page.addImage({data:item.image,x:8.1,y:1.8,w:4.3,h:3.6});page.addText(String(slides.indexOf(item)+1).padStart(2,'0'),{x:11.8,y:6.8,w:.6,h:.25,fontSize:10,color,margin:0});if(item.notes)page.addNotes(item.notes)}
 const output=await pptx.write({outputType:'arraybuffer'});await downloadFile(file.name,output as ArrayBuffer,'pptx');setStatus('PowerPoint export ready.')}catch(error){setStatus('Export failed: '+(error instanceof Error?error.message:String(error)))}finally{setBusy(false)}};
 const importBackup=async(file:File)=>{try{
  if(file.size>50*1024*1024)throw Error('Backup must be smaller than 50 MB.');
  const parsed=JSON.parse(await file.text());
  if(!parsed||typeof parsed!=='object'||!themes.some(t=>t.id===parsed.theme)||!Array.isArray(parsed.slides)||!parsed.slides.length||parsed.slides.length>500)throw Error('Choose a valid Workspace deck backup with 1 to 500 slides.');
  const safeSlides:Slide[]=parsed.slides.map((s:unknown)=>{
   if(!s||typeof s!=='object'||Array.isArray(s))throw Error('Invalid slide in backup.');
   const item=s as Record<string,unknown>;
   for(const key of ['id','title','body','right','notes'])if(typeof item[key]!=='string'||(item[key] as string).length>(key==='id'?200:100000))throw Error('Invalid or oversized slide '+key+'.');
   if(!['title','content','columns'].includes(item.layout as string))throw Error('Invalid slide layout.');
   if(item.background!==undefined&&(typeof item.background!=='string'||!/^#[0-9a-fA-F]{6}$/.test(item.background)))throw Error('Invalid slide background.');
   if(item.image!==undefined&&(typeof item.image!=='string'||item.image.length>14*1024*1024||!/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(item.image)))throw Error('Images must be local PNG, JPEG, or WebP data smaller than 10 MB.');
   return {id:crypto.randomUUID(),title:item.title as string,body:item.body as string,right:item.right as string,notes:item.notes as string,layout:item.layout as Slide['layout'],...(item.background?{background:item.background as string}:{}),...(item.image?{image:item.image as string}:{})};
  });
  if(slides.length&&!window.confirm('Replace this deck with the imported backup? Export a backup first if you want to keep the current slides.'))return;
  save({theme:parsed.theme,slides:safeSlides});setSelected(0);setStatus('Deck imported.');
 }catch(e){setStatus(e instanceof Error?e.message:'Could not read backup.')}};
 const loadImage=(file:File)=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setStatus('Choose a PNG, JPEG, or WebP image.');return}if(file.size>10*1024*1024){setStatus('Please use an image smaller than 10 MB.');return}const reader=new FileReader();reader.onload=()=>patch({image:String(reader.result)});reader.readAsDataURL(file)};
 const renderSlide=(item:Slide,mini=false)=>{const style={'--slide-bg':item.background||theme.bg,'--slide-fg':theme.fg,'--slide-accent':theme.accent} as React.CSSProperties;return <div className={`pe-slide pe-layout-${item.layout} ${item.image?'pe-has-image':''} ${mini?'pe-mini':''}`} style={style}><div className="pe-slide-rule"/><div className="pe-slide-content">{mini||present?<h2>{item.title}</h2>:<textarea aria-label="Slide title" className="pe-title-input" value={item.title} onChange={e=>patch({title:e.target.value})} spellCheck/>}<div className="pe-body-columns">{mini||present?<p>{item.body}</p>:<textarea aria-label="Slide body" value={item.body} onChange={e=>patch({body:e.target.value})}/>} {item.layout==='columns'&&!item.image&&(mini||present?<p>{item.right}</p>:<textarea aria-label="Right column" value={item.right||''} onChange={e=>patch({right:e.target.value})}/>)}</div></div>{item.image&&<img src={item.image} alt="Slide visual"/>}<span className="pe-slide-number">{String(slides.indexOf(item)+1).padStart(2,'0')}</span></div>};
 return <div className="presentation-editor"><div className="pe-toolbar"><div className="pe-tool-group" role="group" aria-label="History"><span className="pe-group-label">History</span><button aria-label="Undo" title="Undo · Ctrl+Z" disabled={!history.current.past.length} onClick={()=>travel()}><Undo2 size={16}/></button><button aria-label="Redo" title="Redo · Ctrl+Y" disabled={!history.current.future.length} onClick={()=>travel(true)}><Redo2 size={16}/></button></div><div className="pe-tool-group" role="group" aria-label="Slide actions"><span className="pe-group-label">Slides</span><button onClick={add}><Plus size={16}/>New slide</button><button title="Duplicate slide" aria-label="Duplicate slide" onClick={duplicate}><Copy size={16}/></button><button title="Delete slide" aria-label="Delete slide" disabled={slides.length===1} onClick={remove}><Trash2 size={16}/></button></div><div className="pe-tool-group" role="group" aria-label="Insert and files"><span className="pe-group-label">Insert & files</span><button onClick={()=>imageInput.current?.click()}><ImagePlus size={16}/>Image</button><button onClick={()=>backupInput.current?.click()} title="Import Workspace JSON backup"><Upload size={16}/>Import</button><button onClick={()=>downloadFile(file.name,JSON.stringify(data,null,2),'json').catch(e=>setStatus(String(e)))} title="Export Workspace JSON backup">Backup</button></div><div className="pe-tool-group pe-export" role="group" aria-label="Share and present"><span className="pe-group-label">Deliver</span><button onClick={exportPptx} disabled={busy}><Download size={16}/>{busy?'Exporting…':'Export PPTX'}</button><button className="pe-primary" onClick={start}><Play size={15}/>Present</button></div></div>
 <div className="pe-workspace"><aside className="pe-filmstrip"><div className="pe-strip-heading">SLIDES <span>{slides.length}</span></div>{slides.map((item,i)=><button className={`pe-thumbnail ${i===index?'active':''}`} key={item.id} onClick={()=>setSelected(i)} aria-label={`Select slide ${i+1}: ${item.title}`}><span className="pe-thumb-index">{i+1}</span>{renderSlide(item,true)}</button>)}<button className="pe-add-slide" onClick={add}><Plus size={17}/>Add slide</button><div className="pe-reorder"><button aria-label="Move slide up" disabled={!index} onClick={()=>move(-1)}><ChevronUp size={16}/>Up</button><button aria-label="Move slide down" disabled={index===slides.length-1} onClick={()=>move(1)}><ChevronDown size={16}/>Down</button></div></aside>
 <main className="pe-main"><div className="pe-canvas-caption"><span>SLIDE {index+1} <span className="pe-muted">/ {slides.length}</span></span><span>Click the text to make it yours</span></div><div className="pe-canvas">{renderSlide(slide)}</div><div className="pe-notes"><label htmlFor="pe-speaker-notes">Speaker notes</label><textarea id="pe-speaker-notes" value={slide.notes||''} placeholder="Add talking points for this slide. Notes stay off the presentation screen." onChange={e=>patch({notes:e.target.value})}/></div>{status&&<div className="pe-status" role="status">{status}<button aria-label="Dismiss message" onClick={()=>setStatus('')}><X size={14}/></button></div>}</main>
 <aside className="pe-inspector"><div className="pe-inspector-title">Slide design</div><label>LAYOUT</label><select aria-label="Slide layout" value={slide.layout} onChange={e=>patch({layout:e.target.value as Slide['layout']})}><option value="title">Title & subtitle</option><option value="content">Title & content</option><option value="columns">Two columns</option></select><label>DECK THEME</label><div className="pe-themes">{themes.map(t=><button key={t.id} aria-pressed={data.theme===t.id} className={data.theme===t.id?'chosen':''} onClick={()=>save({...data,theme:t.id})}><span style={{background:t.bg,color:t.fg}}>Aa<span style={{background:t.accent}}/></span>{t.name}</button>)}</div><label htmlFor="pe-background">SLIDE BACKGROUND</label><div className="pe-color"><input id="pe-background" type="color" value={slide.background||theme.bg} onChange={e=>patch({background:e.target.value})}/><span>{slide.background||theme.bg}</span><button onClick={()=>patch({background:undefined})}>Reset</button></div>{slide.image&&<button className="pe-remove-image" onClick={()=>patch({image:undefined})}><Trash2 size={14}/>Remove image</button>}<div className="pe-design-tip">A strong slide starts with one clear idea.<br/><br/>Export to PowerPoint to continue editing anywhere.</div></aside></div>
 <input ref={imageInput} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{if(e.target.files?.[0])loadImage(e.target.files[0]);e.target.value=''}}/><input ref={backupInput} type="file" hidden accept=".json" onChange={e=>{if(e.target.files?.[0])void importBackup(e.target.files[0]);e.target.value=''}}/>
 <div ref={stage} className={`pe-present ${present?'is-presenting':''}`}>{present&&<>{renderSlide(slide)}<div className="pe-present-controls"><button aria-label="Previous slide" disabled={!index} onClick={()=>setSelected(index-1)}><ArrowLeft size={20}/></button><span>{index+1} / {slides.length}</span><button aria-label="Next slide" disabled={index===slides.length-1} onClick={()=>setSelected(index+1)}><ArrowRight size={20}/></button><button onClick={end}><X size={18}/>Exit <kbd>Esc</kbd></button></div></>}</div></div>
}


