'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const cli = path.resolve(__dirname, '../agent/cli.cjs');
function run(workspace, ...args) { return spawnSync(process.execPath, [cli, '--workspace', workspace, ...args], { encoding: 'utf8', timeout: 15000, windowsHide: true }); }
test('CLI requires explicit workspace and rejects invalid commands', async t => {
  const workspace = await fs.mkdtemp(path.join(os.tmpdir(), 'folio-cli-'));
  t.after(() => fs.rm(workspace, { recursive: true, force: true }));
  const missing = spawnSync(process.execPath, [cli, 'capabilities'], { encoding: 'utf8' });
  assert.equal(missing.status, 1);
  assert.equal(JSON.parse(missing.stderr).error.code, 'WORKSPACE_REQUIRED');
  const invalid = run(workspace, 'exec', '--json', '{"operation":"shell.exec"}');
  assert.equal(invalid.status, 1);
  assert.equal(JSON.parse(invalid.stderr).error.code, 'UNKNOWN_OPERATION');
  const capabilities = run(workspace, 'capabilities');
  assert.equal(capabilities.status, 0, capabilities.stderr);
  assert.ok(JSON.parse(capabilities.stdout).operations.some(t=>t.operation==='file.restore')); 
  const payloadPath = path.join(workspace, 'too-large.json');
  await fs.writeFile(payloadPath, ' '.repeat(1024 * 1024 + 1));
  const large = run(workspace, 'exec', '--file', payloadPath);
  assert.equal(JSON.parse(large.stderr).error.code, 'PAYLOAD_TOO_LARGE');
});
test('CLI persists a created file between separate processes', async t => {
  const workspace = await fs.mkdtemp(path.join(os.tmpdir(), 'folio-cli-'));
  t.after(() => fs.rm(workspace, { recursive: true, force: true }));
  const created = run(workspace, 'exec', '--json', JSON.stringify({ operation: 'file.create', kind: 'document', name: 'Transport proof', requestId: 'cli-create-proof' }));
  assert.equal(created.status, 0, created.stderr);
  const listed = run(workspace, 'exec', '--json', '{"operation":"workspace.list"}');
  assert.equal(listed.status, 0, listed.stderr);
  const entry = JSON.parse(listed.stdout).files.find(file => file.name === 'Transport proof');
  assert.ok(entry);
  const read = run(workspace, 'exec', '--json', JSON.stringify({ operation: 'file.read', fileId: entry.id }));
  assert.equal(read.status, 0, read.stderr);
  assert.match(read.stdout, /Transport proof/);
});
test('real MCP stdio initialize, discover tools, create and read', { timeout: 20000 }, async t => {
  const { Client } = require('@modelcontextprotocol/sdk/client/index.js');
  const { StdioClientTransport } = require('@modelcontextprotocol/sdk/client/stdio.js');
  const workspace = await fs.mkdtemp(path.join(os.tmpdir(), 'folio-mcp-'));
  const client = new Client({ name: 'folio-proof', version: '1.0.0' });
  t.after(async () => { await client.close(); await fs.rm(workspace, { recursive: true, force: true }); });
  await client.connect(new StdioClientTransport({ command: process.execPath, args: [cli, '--workspace', workspace, 'mcp'], stderr: 'pipe' }));
  const { tools } = await client.listTools();
  assert.ok(tools.some(t=>t.name==='file_restore')); assert.ok(tools.some(t=>t.name==='document_format')); 
  assert.ok(tools.find(tool => tool.name === 'file_create').inputSchema.required.includes('requestId'));
  assert.equal(tools.find(tool => tool.name === 'file_read').annotations.readOnlyHint, true);
  assert.equal(tools.find(tool => tool.name === 'spreadsheet_write').annotations.destructiveHint, true);
  const created = await client.callTool({ name: 'file_create', arguments: { kind: 'document', name: 'MCP proof', requestId: 'mcp-create-proof' } });
  assert.ok(!created.isError, JSON.stringify(created));
  assert.ok(created.structuredContent);
  const listed = await client.callTool({ name: 'workspace_list', arguments: {} });
  const entry = listed.structuredContent.files.find(file => file.name === 'MCP proof');
  assert.ok(entry);
  const read = await client.callTool({ name: 'file_read', arguments: { fileId: entry.id } });
  assert.ok(!read.isError);
  assert.match(JSON.stringify(read.structuredContent), /MCP proof/);
  const invalid = await client.callTool({ name: 'file_create', arguments: { kind: 'document', name: 'Missing request token' } });
  assert.equal(invalid.isError, true);
});
