'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const JSZip=require('jszip');const {exportFile,importFile}=require('../core/formats.cjs');
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
const text=(s,marks)=>({type:'text',text:s,...(marks?{marks:marks.map(type=>({type}))}:{})});const para=s=>({type:'paragraph',content:[text(s)]});
const file={name:'Semantic fixture',kind:'document',data:{content:{type:'doc',content:[{type:'heading',attrs:{level:2},content:[text('Heading')]},{type:'paragraph',content:[text('Marked',['bold','italic','underline'])]},{type:'orderedList',attrs:{start:3},content:[{type:'listItem',content:[para('Numbered')]}]},{type:'bulletList',content:[{type:'listItem',content:[para('Bullet')]}]},{type:'table',content:[{type:'tableRow',content:[{type:'tableCell',content:[para('Cell')]}]}]},{type:'image',attrs:{src:png,alt:'pixel'}}]}}};
test('DOCX contains semantic marks, heading, editable numbering, table and actual image relationship; imports back',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'folio-formats-'));try{const dest=path.join(dir,'test.docx');await exportFile(file,'docx',dest);const zip=await JSZip.loadAsync(await fs.readFile(dest));const xml=await zip.file('word/document.xml').async('string');for(const token of ['Heading2','<w:b','<w:i','<w:u','<w:numPr','<w:tbl','<w:drawing'])assert.ok(xml.includes(token),token);const numbering=await zip.file('word/numbering.xml').async('string');assert.ok(numbering.includes('decimal'));assert.ok(numbering.includes('bullet'));assert.ok(Object.keys(zip.files).some(n=>/word\/media\/.+\.png$/.test(n)));const imported=await importFile(dest,'document');const content=JSON.stringify(imported.data.content);for(const token of ['heading','bold','italic','underline','orderedList','bulletList','table','data:image/png;base64'])assert.ok(content.includes(token),token);await assert.rejects(exportFile(file,'docx',dest),{code:'OUTPUT_EXISTS'});}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('HTML roundtrip retains semantic structure and embedded image, strips scripts, events and external images',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'folio-formats-'));try{const dest=path.join(dir,'test.html');await exportFile(file,'html',dest);const html=await fs.readFile(dest,'utf8');for(const token of ['<h2>','<strong>','<em>','<u>','<ol','<ul','<table>','<img'])assert.ok(html.includes(token));await fs.appendFile(dest,'<script>alert(1)</script><p onclick="bad()">Safe</p><img src="https://bad.test/tracker"><iframe>Secret</iframe>');const imported=await importFile(dest,'document');const content=JSON.stringify(imported.data.content);for(const token of ['heading','orderedList','table','image','Safe'])assert.ok(content.includes(token));for(const token of ['alert(1)','onclick','bad.test','Secret'])assert.ok(!content.includes(token));}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('XLSX basic cell formatting survives export and import',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'folio-formats-'));try{const dest=path.join(dir,'styled.xlsx');await exportFile({kind:'spreadsheet',data:{sheets:[{id:'one',name:'Sheet1',cells:[['12']],styles:{A1:{bold:true,italic:true,numberFormat:'0.00',fill:'#ffeeaa',color:'#112233',align:'right'}}}]}},'xlsx',dest);const ExcelJS=require('exceljs');const book=new ExcelJS.Workbook();await book.xlsx.readFile(dest);const cell=book.worksheets[0].getCell('A1');assert.equal(cell.font.bold,true);assert.equal(cell.numFmt,'0.00');assert.equal(cell.fill.fgColor.argb,'FFFFEEAA');const imported=await importFile(dest,'spreadsheet');assert.deepEqual(imported.data.sheets[0].styles.A1,{bold:true,italic:true,numberFormat:'0.00',color:'#112233',fill:'#FFEEAA',align:'right'});}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('HTML imports satisfy the editor schema for code blocks, repeated marks and canonical embedded images',()=>{
 const {getSchema}=require('@tiptap/core');const schema=getSchema([require('@tiptap/starter-kit').default,require('@tiptap/extension-table').TableKit,require('@tiptap/extension-image').default,require('@tiptap/extension-text-align').default.configure({types:['heading','paragraph']})]);const {fromHtml}=require('../core/document-format.cjs');const {dataValid}=require('../core/engine.cjs');
 const html='<pre><code><strong>const x = 1;<br>next</strong></code></pre><p><em><b><strong>nested</strong></b></em><code><b>code</b></code></p>';
 const doc=fromHtml(html);assert.doesNotThrow(()=>schema.nodeFromJSON(doc).check());assert.deepEqual(doc.content[0].content,[{type:'text',text:'const x = 1;\nnext'}]);assert.deepEqual(doc.content[1].content[0].marks,[{type:'bold'},{type:'italic'}]);
 const jpegBytes=Buffer.from([255,216,255,224,0,0,255,217]);for(const [input,expected] of [[png.replace('data:image/png','DATA:IMAGE/JPG').replace('base64,','BASE64,\n'),png],['DATA:IMAGE/JPG;BASE64, '+jpegBytes.toString('base64')+'\n','data:image/jpeg;base64,'+jpegBytes.toString('base64')]]){const content=fromHtml('<p><img src="'+input+'"></p>');assert.equal(content.content[0].attrs.src,expected);assert.doesNotThrow(()=>schema.nodeFromJSON(content).check());assert.doesNotThrow(()=>dataValid('document',{content}));}
});
