const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const {exportFile,importFile}=require('../core/formats.cjs');
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'folio-formats-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return dir;}
const document={name:'Report',kind:'document',data:{content:{type:'doc',content:[{type:'heading',attrs:{level:1},content:[{type:'text',text:'Quarterly report'}]},{type:'paragraph',content:[{type:'text',text:'Hello & goodbye',marks:[{type:'bold'}]}]}]}}};
test('DOCX creates real package and reads paragraph text',async t=>{const dir=await fixture(t),p=path.join(dir,'report.docx');const result=await exportFile(document,'docx',p);assert.equal(result.sha256.length,64);assert.ok(result.bytes>100);const back=await importFile(p);assert.match(JSON.stringify(back.data),/Quarterly report/);assert.match(JSON.stringify(back.data),/Hello & goodbye/);assert.ok(back.warnings.length);});
test('all kinds roundtrip JSON data and existing output is untouched',async t=>{const dir=await fixture(t);for(const kind of ['document','spreadsheet','presentation','notebook']){const file={name:kind,kind,data:{custom:['x',1,{nested:true}]}};const p=path.join(dir,kind+'.json');await exportFile(file,'json',p);assert.deepEqual((await importFile(p)).data,file.data);const before=await fs.readFile(p);await assert.rejects(exportFile({...file,name:'changed'},'json',p),{code:'OUTPUT_EXISTS'});assert.deepEqual(await fs.readFile(p),before);}});
test('XLSX retains scalar values and formulas with cached calculation',async t=>{const dir=await fixture(t),p=path.join(dir,'book.xlsx');const file={name:'Book',kind:'spreadsheet',data:{sheets:[{id:'s',name:'Sheet1',cells:[['2','3','=SUM(A1:B1)'],['001','true','=A1*B1']]}],activeSheet:'s'}};await exportFile(file,'xlsx',p);const ExcelJS=require('exceljs');const book=new ExcelJS.Workbook();await book.xlsx.readFile(p);assert.equal(book.worksheets[0].getCell('C1').result,5);assert.equal(book.worksheets[0].getCell('A2').value,'001');const back=await importFile(p);assert.deepEqual(back.data.sheets[0].cells,file.data.sheets[0].cells);});
test('CSV quoted commas newlines quotes and trailing empty cells roundtrip',async t=>{const dir=await fixture(t),p=path.join(dir,'data.csv');const cells=[['a,b','line\nline','"quoted"',''],['x','','z','']];await exportFile({name:'CSV',kind:'spreadsheet',data:{sheets:[{id:'s',name:'S',cells}],activeSheet:'s'}},'csv',p);assert.deepEqual((await importFile(p)).data.sheets[0].cells,cells);await fs.writeFile(path.join(dir,'bad.csv'),'"unclosed');await assert.rejects(importFile(path.join(dir,'bad.csv')),{code:'INVALID_INPUT'});});
test('PPTX contains slides and notes in OOXML archive',async t=>{const dir=await fixture(t),p=path.join(dir,'deck.pptx');await exportFile({name:'Deck',kind:'presentation',data:{theme:'cobalt',slides:[{id:'s',title:'Hello slides',body:'Useful body',notes:'Presenter note',layout:'content'}]}},'pptx',p);const JSZip=require('jszip');const zip=await JSZip.loadAsync(await fs.readFile(p));assert.match(await zip.file('ppt/slides/slide1.xml').async('string'),/Hello slides/);assert.match(await zip.file('ppt/notesSlides/notesSlide1.xml').async('string'),/Presenter note/);await assert.rejects(importFile(p),{code:'INVALID_FORMAT'});});
test('HTML export escapes markup and unsupported export never creates output',async t=>{const dir=await fixture(t),p=path.join(dir,'a.html');await exportFile(document,'html',p);assert.match(await fs.readFile(p,'utf8'),/Hello &amp; goodbye/);const rejected=path.join(dir,'a.pdf');await assert.rejects(exportFile(document,'pdf',rejected),{code:'INVALID_FORMAT'});await assert.rejects(fs.access(rejected));});
