'use strict';
const imagePattern=/^data:image\/(png|jpeg|jpg);base64,([a-zA-Z0-9+/=\s]+)$/i;
const escape=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function imageData(src){const m=imagePattern.exec(src||'');if(!m)return null;const bytes=Buffer.from(m[2],'base64');if(bytes.length>10*1024*1024)return null;const png=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!png&&!jpg)return null;return {bytes,type:png?'png':'jpg'};}
// A non-strict streaming HTML parser. Only allowlisted semantic nodes are rebuilt;
// no source markup, event attributes, CSS, URLs or executable nodes are retained.
function fromHtml(html,warnings=[]){
 const parser=require('sax').parser(false,{lowercase:true,trim:false,normalize:false});const root={tag:'root',children:[]};const stack=[root];let count=0;
 parser.onopentag=n=>{if(++count>100000||stack.length>128)throw Object.assign(new Error('HTML structure exceeds limits'),{code:'LIMIT_EXCEEDED'});const tag=n.name.toLowerCase();if(tag==='p'&&stack.at(-1).tag==='p')stack.pop();if(tag==='li'&&stack.at(-1).tag==='li')stack.pop();const node={tag,attrs:n.attributes,children:[]};stack.at(-1).children.push(node);if(!['br','img','hr','meta','link','input','wbr','source','area','base','embed'].includes(tag))stack.push(node);};
 parser.onclosetag=tag=>{tag=tag.toLowerCase();for(let i=stack.length-1;i>0;i--)if(stack[i].tag===tag){stack.length=i;break;}};
 parser.ontext=t=>stack.at(-1).children.push({text:t});parser.oncdata=()=>{};parser.onerror=()=>{parser.resume();};parser.write('<folio-root>'+String(html).replace(/<!doctype[^>]*>/gi,'')+'</folio-root>').close();
 const blocked=new Set(['script','style','iframe','object','embed','svg','math','form','template','noscript']);
 function convert(n,marks=[]){if(n.text!=null)return n.text?[{type:'text',text:n.text,...(marks.length?{marks}: {})}]:[];if(blocked.has(n.tag)){warnings.push('Unsafe HTML content was omitted.');return [];}
 const mark={b:'bold',strong:'bold',i:'italic',em:'italic',u:'underline',s:'strike',del:'strike',code:'code'}[n.tag];const next=mark?(mark==='code'?[{type:'code'}]:marks.some(m=>m.type==='code'||m.type===mark)?marks:[...marks,{type:mark}].sort((a,b)=>['bold','code','italic','strike','underline'].indexOf(a.type)-['bold','code','italic','strike','underline'].indexOf(b.type))):marks;const children=()=>n.children.flatMap(c=>convert(c,next));
 if(n.tag==='img'){const image=imageData(n.attrs.src);if(!image){warnings.push('External or unsupported images were omitted; use embedded PNG/JPEG data URLs.');return [];}return [{type:'image',attrs:{src:'data:image/'+(image.type==='jpg'?'jpeg':'png')+';base64,'+image.bytes.toString('base64'),alt:n.attrs.alt||'',...(Number(n.attrs.width)>0?{width:Math.min(2000,Number(n.attrs.width))}:{}),...(Number(n.attrs.height)>0?{height:Math.min(2000,Number(n.attrs.height))}:{})}}];}
 if(n.tag==='br')return [{type:'hardBreak'}];if(n.tag==='hr')return [{type:'horizontalRule'}];
 const types={p:'paragraph',h1:'heading',h2:'heading',h3:'heading',h4:'heading',h5:'heading',h6:'heading',ul:'bulletList',ol:'orderedList',li:'listItem',table:'table',tr:'tableRow',td:'tableCell',th:'tableHeader',blockquote:'blockquote',pre:'codeBlock'};const type=types[n.tag];if(!type)return children();let content=children();let attrs;
 if(type==='codeBlock'){const plain=nodes=>nodes.map(c=>c.type==='text'?c.text:c.type==='hardBreak'?'\n':plain(c.content||[])).join('');const value=plain(content);content=value?[{type:'text',text:value}]:[];}if(type==='heading')attrs={level:Number(n.tag[1])};if(type==='orderedList')attrs={start:Math.max(1,Number(n.attrs.start)||1)};
 if(type==='tableCell'||type==='tableHeader'){attrs={colspan:Math.max(1,Math.min(100,Number(n.attrs.colspan)||1)),rowspan:Math.max(1,Math.min(100,Number(n.attrs.rowspan)||1))};content=wrap(content);}
 if(type==='paragraph'&&content.some(c=>c.type==='image'))return wrap(content);if(['listItem','blockquote'].includes(type))content=wrap(content);if(['bulletList','orderedList','table','tableRow'].includes(type))content=content.filter(c=>c.type!=='text');return [{type,...(attrs?{attrs}:{}),content}];}
 function wrap(nodes){const out=[];let inline=[];const flush=()=>{if(inline.some(n=>n.type!=='text'||n.text.trim()))out.push({type:'paragraph',content:inline});inline=[];};for(const n of nodes){if(['text','hardBreak'].includes(n.type))inline.push(n);else{flush();out.push(n);}}flush();return out.length?out:[{type:'paragraph',content:[]}];}
 return {type:'doc',content:wrap(root.children.flatMap(n=>convert(n)))};
}
function toHtml(doc,warnings=[]){function render(n){if(n.type==='text'){let value=escape(n.text);for(const m of n.marks||[]){const tag={bold:'strong',italic:'em',underline:'u',strike:'s',code:'code'}[m.type];if(tag)value=`<${tag}>${value}</${tag}>`;else warnings.push(`Unsupported text mark ${m.type} omitted.`);}return value;}if(n.type==='hardBreak')return '<br>';if(n.type==='horizontalRule')return '<hr>';if(n.type==='image'){if(!imageData(n.attrs?.src)){warnings.push('External or unsupported images omitted.');return '';}return `<img src="${escape(n.attrs.src)}" alt="${escape(n.attrs.alt)}">`;}
 const tag={doc:'',paragraph:'p',heading:'h'+Math.max(1,Math.min(6,n.attrs?.level||1)),bulletList:'ul',orderedList:'ol',listItem:'li',table:'table',tableRow:'tr',tableCell:'td',tableHeader:'th',blockquote:'blockquote',codeBlock:'pre'}[n.type];const body=(n.content||[]).map(render).join('');if(tag===undefined){warnings.push(`Unsupported HTML node ${n.type} omitted.`);return body;}let attrs='';if(n.type==='orderedList')attrs=` start="${Math.max(1,Number(n.attrs?.start)||1)}"`;if(['tableCell','tableHeader'].includes(n.type))attrs=` colspan="${Math.max(1,Number(n.attrs?.colspan)||1)}" rowspan="${Math.max(1,Number(n.attrs?.rowspan)||1)}"`;return tag?`<${tag}${attrs}>${body}</${tag}>`:body;}
 return '<!doctype html><html><head><meta charset="utf-8"></head><body>'+render(doc)+'</body></html>';
}
async function toDocx(doc,warnings=[]){const D=require('docx');const numbering=[];let listId=0;
 function image(n){const data=imageData(n.attrs?.src);if(!data){warnings.push('External or unsupported images omitted from DOCX.');return [];}let width=Number(n.attrs?.width)||320,height=Number(n.attrs?.height)||200;if(data.type==='png'&&data.bytes.length>=24){const w=data.bytes.readUInt32BE(16),h=data.bytes.readUInt32BE(20);if(w&&h){width=Number(n.attrs?.width)||Math.min(w,600);height=Number(n.attrs?.height)||width*h/w;}}return [new D.ImageRun({data:data.bytes,type:data.type,transformation:{width:Math.min(1000,width),height:Math.min(1000,height)}})];}
 function runs(n){if(n.type==='image')return image(n);if(n.type==='text'){const marks=n.marks||[];return [new D.TextRun({text:n.text||'',bold:marks.some(m=>m.type==='bold'),italics:marks.some(m=>m.type==='italic'),strike:marks.some(m=>m.type==='strike'),underline:marks.some(m=>m.type==='underline')?{}:undefined})];}if(n.type==='hardBreak')return [new D.TextRun({break:1})];return (n.content||[]).flatMap(runs);}
 function blocks(nodes,level=0){return nodes.flatMap(n=>{if(['paragraph','heading','codeBlock','image'].includes(n.type))return [new D.Paragraph({children:runs(n),heading:n.type==='heading'?D.HeadingLevel['HEADING_'+Math.max(1,Math.min(6,n.attrs?.level||1))]:undefined,alignment:n.attrs?.textAlign})];if(['bulletList','orderedList'].includes(n.type)){const reference='list'+listId++;const current=Math.min(8,level);numbering.push({reference,levels:Array.from({length:9},(_,i)=>({level:i,format:n.type==='bulletList'?D.LevelFormat.BULLET:D.LevelFormat.DECIMAL,text:n.type==='bulletList'?'•':`%${i+1}.`,start:Math.max(1,Number(n.attrs?.start)||1),alignment:D.AlignmentType.LEFT,style:{paragraph:{indent:{left:720*(i+1),hanging:260}}}}))});return (n.content||[]).flatMap(item=>{let first=true;return (item.content||[]).flatMap(c=>{if(['bulletList','orderedList'].includes(c.type))return blocks([c],level+1);if(first&&['paragraph','heading'].includes(c.type)){first=false;return [new D.Paragraph({children:runs(c),numbering:{reference,level:current}})];}return blocks([c],level);});});}if(n.type==='table')return [new D.Table({rows:(n.content||[]).map(row=>new D.TableRow({children:(row.content||[]).map(cell=>new D.TableCell({columnSpan:cell.attrs?.colspan||1,children:(()=>{const b=blocks(cell.content||[]);return b.length?b:[new D.Paragraph('')];})()}))}))})];if(n.type==='blockquote')return blocks(n.content||[],level);warnings.push(`Unsupported DOCX node ${n.type} omitted.`);return [];});}
 const children=blocks(doc.content||[]);warnings.push('DOCX preserves basic marks, headings, editable lists, tables and embedded PNG/JPEG images; exact page layout, advanced styles and vertical merged cells are not guaranteed.');return D.Packer.toBuffer(new D.Document({numbering:{config:numbering},sections:[{children}]}));
}
module.exports={fromHtml,toHtml,toDocx};
