const fs=require('node:fs/promises');
const path=require('node:path');
const crypto=require('node:crypto');
const legacy=require('../electron/storage.cjs');

const MAX=100*1024*1024;
const HISTORY_VERSIONS=30,HISTORY_BYTES=20*1024*1024;
function remember(state,file,origin){
 const revision=hash(file);state.history??=[];
 if(state.history.some(h=>h.fileId===file.id&&h.revision===revision))return;
 const snapshot=structuredClone(file);delete snapshot.revision;
 const entry={fileId:file.id,revision,at:new Date().toISOString(),origin,snapshot};if(Buffer.byteLength(JSON.stringify([entry]))>HISTORY_BYTES)return;
 state.history.push(entry);
 let count=0;state.history=state.history.slice().reverse().filter(h=>h.fileId!==file.id||++count<=HISTORY_VERSIONS).reverse();
 let bytes=Buffer.byteLength(JSON.stringify(state.history));while(bytes>HISTORY_BYTES&&state.history.length){state.history.shift();bytes=Buffer.byteLength(JSON.stringify(state.history));}
}
function documentNode(file,nodePath){
 if(file.kind!=='document')fail('WRONG_FILE_TYPE','Needs a document');
 if(!file.data.content)fail('UNSUPPORTED_CONTENT','Open this HTML document in the editor before structured editing');
 if(!Array.isArray(nodePath)||nodePath.length>32||nodePath.some(i=>!Number.isInteger(i)||i<0))fail('INVALID_ARGUMENT','nodePath must contain nonnegative child indexes relative to data.content');
 let node=file.data.content;for(const i of nodePath){node=node.content?.[i];if(!node)fail('NOT_FOUND','Document nodePath does not exist');}return node;
}
function validateMarks(marks){
 if(!Array.isArray(marks)||marks.length>8)fail('INVALID_ARGUMENT','marks must be an array');
 const types=new Set();for(const m of marks){if(!m||!['bold','italic','underline','strike','code'].includes(m.type)||Object.keys(m).some(k=>k!=='type')||types.has(m.type))fail('INVALID_ARGUMENT','Use unique bold, italic, underline, strike or code marks without attributes');types.add(m.type);}return structuredClone(marks);
}
function fail(code,message,details){const e=new Error(message);e.code=code;if(details)e.details=details;throw e;}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().filter(k=>k!=='revision').map(k=>[k,stable(v[k])]));return v;}
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const expose=f=>({...f,revision:hash(f)});
const kinds=['document','spreadsheet','presentation','notebook'];
function str(value,label,max=1000000){if(typeof value!=='string'||value.length>max)fail('INVALID_ARGUMENT',`${label} must be a string of at most ${max} characters`);return value;}
function dataValid(kind,data){
 if(!data||typeof data!=='object'||Array.isArray(data))fail('INVALID_DATA','File data must be an object');
 if(kind==='document'){
  if(data.html!==undefined){str(data.html,'html',5000000);if(/<(?:script|iframe|object|embed)\b|\son\w+\s*=|javascript:/i.test(data.html))fail('INVALID_DATA','Executable HTML is not accepted');}
  if(data.content!==undefined){const allowed=new Set(['doc','paragraph','heading','text','bulletList','orderedList','listItem','blockquote','codeBlock','hardBreak','horizontalRule','image','table','tableRow','tableCell','tableHeader']);let count=0;const walk=(n,depth)=>{if(!n||typeof n!=='object'||depth>32||++count>100000||!allowed.has(n.type))fail('INVALID_DATA','Unsupported or invalid document node');if(n.text!==undefined)str(n.text,'node text');if(n.attrs?.src&&!/^data:image\/(png|jpeg|gif|webp);base64,[A-Za-z0-9+/=]+$/.test(n.attrs.src))fail('INVALID_DATA','Document images must be embedded local images');if(n.content!==undefined){if(!Array.isArray(n.content))fail('INVALID_DATA','Node content must be an array');n.content.forEach(x=>walk(x,depth+1));}};walk(data.content,0);if(data.content.type!=='doc')fail('INVALID_DATA','Document root must be doc');}
 }else if(kind==='spreadsheet'&&data.sheets!==undefined){
  if(!Array.isArray(data.sheets)||!data.sheets.length||data.sheets.length>100)fail('INVALID_DATA','Workbook needs 1 to 100 sheets');const ids=new Set(),names=new Set();
  for(const s of data.sheets){str(s.id,'sheet ID',128);str(s.name,'sheet name',31);if(!s.name||/[\\/?*\[\]:]/.test(s.name)||ids.has(s.id)||names.has(s.name.toLowerCase()))fail('INVALID_DATA','Sheet names and IDs must be unique and valid');ids.add(s.id);names.add(s.name.toLowerCase());if(!Array.isArray(s.cells)||s.cells.length>10000)fail('INVALID_DATA','Sheet exceeds 10000 row limit');for(const row of s.cells){if(!Array.isArray(row)||row.length>1000)fail('INVALID_DATA','Row exceeds 1000 columns');for(const v of row)if(!['string','number','boolean'].includes(typeof v)&&v!==null)fail('INVALID_DATA','Cells require scalar values');}}
 }else if(kind==='presentation'&&data.slides!==undefined){
  if(!Array.isArray(data.slides)||!data.slides.length||data.slides.length>500)fail('INVALID_DATA','Deck needs 1 to 500 slides');const ids=new Set();for(const s of data.slides){str(s.id,'slide ID',128);if(ids.has(s.id))fail('INVALID_DATA','Duplicate slide ID');ids.add(s.id);str(s.title,'slide title',20000);for(const key of ['body','right','notes'])if(s[key]!==undefined)str(s[key],key,50000);if(!['title','content','columns'].includes(s.layout))fail('INVALID_DATA','Invalid slide layout');if(s.background!==undefined&&!/^#[0-9a-f]{6}$/i.test(s.background))fail('INVALID_DATA','Invalid slide background');if(s.image!==undefined&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s.image))fail('INVALID_DATA','Slide images must be embedded local images');}
 }else if(kind==='notebook'&&data.pages!==undefined){if(!Array.isArray(data.pages)||!data.pages.length||data.pages.length>1000)fail('INVALID_DATA','Notebook needs 1 to 1000 pages');const ids=new Set();for(const p of data.pages){str(p.id,'page ID',128);if(ids.has(p.id))fail('INVALID_DATA','Duplicate page ID');ids.add(p.id);str(p.title,'page title',20000);str(p.text,'page text');}}
 return data;
}
function validateFiles(files){legacy.validate(files);for(const f of files){str(f.id,'file ID',128);str(f.name,'file name',300);dataValid(f.kind,f.data);}return files;}
function initialData(kind){if(kind==='document')return {content:{type:'doc',content:[{type:'paragraph'}]}};if(kind==='spreadsheet'){const id=crypto.randomUUID();return{sheets:[{id,name:'Sheet1',cells:[[]],rows:40,cols:16}],activeSheet:id};}if(kind==='presentation')return{theme:'editorial',slides:[{id:crypto.randomUUID(),title:'Untitled slide',body:'',right:'',notes:'',layout:'title'}]};return{pages:[{id:crypto.randomUUID(),title:'Untitled page',text:''}]};}
function cellAddress(input){const m=/^([A-Z]{1,3})([1-9]\d{0,4})$/i.exec(input||'');if(!m)fail('INVALID_RANGE','Use an A1 cell address');let col=0;for(const c of m[1].toUpperCase())col=col*26+c.charCodeAt(0)-64;const row=Number(m[2])-1;if(col>1000||row>=10000)fail('LIMIT_EXCEEDED','Maximum supported range is 10000 rows by 1000 columns');return{row,col:col-1};}
function createEngine(workspaceDir){
 if(typeof workspaceDir!=='string'||!path.isAbsolute(workspaceDir))fail('WORKSPACE_REQUIRED','Choose an absolute workspace directory');
 const dir=path.resolve(workspaceDir),statePath=path.join(dir,'workspace.state.json');
 async function read(){try{const stat=await fs.stat(statePath);if(stat.size>MAX)fail('LIMIT_EXCEEDED','Workspace exceeds 100 MB');const s=JSON.parse(await fs.readFile(statePath,'utf8'));if(s.version!==2||!Array.isArray(s.receipts)||!Array.isArray(s.audit))fail('CORRUPT_WORKSPACE','Unsupported workspace state');validateFiles(s.files);return s;}catch(e){if(e.code==='ENOENT')return{version:2,files:validateFiles(await legacy.load(dir)),receipts:[],audit:[]};if(e.code&&e.code!=='ENOENT')throw e;fail('CORRUPT_WORKSPACE','Workspace could not be parsed. Original files have been preserved.');}}
 async function transaction(fn){
  await fs.mkdir(dir,{recursive:true});const lock=path.join(dir,'workspace.lock');let handle;
  for(let n=0;n<80;n++){try{handle=await fs.open(lock,'wx');break;}catch(e){const contention=e.code==='EEXIST'||(process.platform==='win32'&&e.code==='EPERM')||(e.code==='EACCES'&&await fs.stat(lock).then(()=>true,()=>false));if(!contention)throw e;if(n===79)fail('WORKSPACE_BUSY','Workspace is locked. Retry after the active writer finishes; inspect the lock if its owner exited.');await new Promise(r=>setTimeout(r,25+Math.floor(Math.random()*15)));}}
  try{await handle.writeFile(JSON.stringify({pid:process.pid,startedAt:new Date().toISOString()}));const state=await read();const outcome=await fn(state);if(outcome.noWrite)return outcome.result;validateFiles(state.files);const json=JSON.stringify(state);if(Buffer.byteLength(json)>MAX)fail('LIMIT_EXCEEDED','Workspace exceeds 100 MB including recovery receipts');
   const pending=statePath+'.'+crypto.randomUUID()+'.pending';const out=await fs.open(pending,'wx');try{await out.writeFile(json,'utf8');await out.sync();}finally{await out.close();}try{await fs.copyFile(statePath,path.join(dir,'workspace.state.previous.json'));}catch(e){if(e.code!=='ENOENT')throw e;}await fs.rename(pending,statePath);return outcome.result;
  }finally{await handle.close();await fs.unlink(lock);}
 }
 const get=(state,id)=>{const f=state.files.find(x=>x.id===id);if(!f)fail('NOT_FOUND','File not found: '+id);return f;};
 const check=(file,revision)=>{if(typeof revision!=='string')fail('REVISION_REQUIRED','Read the file and pass its expectedRevision before editing');if(hash(file)!==revision)fail('REVISION_CONFLICT','This file changed since it was read. Read it again before editing.',{fileId:file.id,currentRevision:hash(file)});};
 const selectSheet=(file,id)=>{if(file.kind!=='spreadsheet')fail('WRONG_FILE_TYPE','This operation needs a spreadsheet');const sheets=file.data.sheets||[];const s=id?sheets.find(x=>x.id===id||x.name===id):sheets.find(x=>x.id===file.data.activeSheet)||sheets[0];if(!s)fail('NOT_FOUND','Sheet not found');return s;};
 async function execute(command){
  if(!command||typeof command!=='object'||typeof command.operation!=='string')fail('INVALID_COMMAND','A command requires an operation');if(Buffer.byteLength(JSON.stringify(command))>25*1024*1024)fail('LIMIT_EXCEEDED','Command exceeds 25 MB');const op=command.operation;
  if(op==='workspace.list'){const state=await read();const all=state.files.filter(f=>(!command.kind||f.kind===command.kind)&&(!command.query||f.name.toLowerCase().includes(command.query.toLowerCase())));const offset=Math.max(0,command.offset||0),limit=Math.min(1000,Math.max(1,command.limit||100));return{files:all.slice(offset,offset+limit).map(f=>({id:f.id,name:f.name,kind:f.kind,updatedAt:f.updatedAt,revision:hash(f)})),workspace:dir,total:all.length,nextOffset:offset+limit<all.length?offset+limit:null};}
  if(op==='workspace.search'){const query=str(command.query,'query',200).toLowerCase();if(!query.trim())fail('INVALID_ARGUMENT','Search query must not be empty');const state=await read(),matches=[];const max=Math.min(100,Math.max(1,command.limit||25));for(const f of state.files){if(command.kind&&f.kind!==command.kind)continue;const add=(text,location)=>{const value=String(text||'');const at=value.toLowerCase().indexOf(query);if(at>=0&&matches.length<max)matches.push({fileId:f.id,name:f.name,kind:f.kind,revision:hash(f),location,snippet:value.slice(Math.max(0,at-60),at+160)});};add(f.name,'name');if(f.kind==='document'){const walk=(n,loc)=>{if(n.text)add(n.text,loc);(n.content||[]).forEach((x,i)=>walk(x,loc+'.'+i));};if(f.data.content)walk(f.data.content,'document');if(f.data.html)add(f.data.html.replace(/<[^>]+>/g,' '),'document');}if(f.kind==='spreadsheet')for(const s of f.data.sheets||[])for(let r=0;r<s.cells.length&&matches.length<max;r++)for(let c=0;c<s.cells[r].length&&matches.length<max;c++)add(s.cells[r][c],{sheetId:s.id,row:r+1,column:c+1});if(f.kind==='presentation')for(const s of f.data.slides||[])for(const field of ['title','body','right','notes'])add(s[field],{slideId:s.id,field});if(f.kind==='notebook')for(const p of f.data.pages||[]){add(p.title,{pageId:p.id,field:'title'});add(p.text,{pageId:p.id,field:'text'});}if(matches.length>=max)break;}return{query:command.query,matches,limit:max,truncated:matches.length===max};}
  if(op==='file.inspect'){const f=get(await read(),command.fileId);const data=f.data;return{fileId:f.id,name:f.name,kind:f.kind,revision:hash(f),updatedAt:f.updatedAt,summary:f.kind==='spreadsheet'?{sheets:(data.sheets||[]).map(s=>({id:s.id,name:s.name,rows:s.cells.length,columns:Math.max(0,...s.cells.map(r=>r.length))}))}:f.kind==='presentation'?{slides:(data.slides||[]).map(s=>({id:s.id,title:s.title,layout:s.layout}))}:f.kind==='notebook'?{pages:(data.pages||[]).map(p=>({id:p.id,title:p.title}))}:{blocks:data.content?.content?.length||0,hasHtml:!!data.html},formats:{document:['docx','txt','md','html','json'],spreadsheet:['xlsx','csv','json'],presentation:['pptx','json'],notebook:['txt','md','json']}[f.kind]};}
  if(op==='workspace.audit'){const state=await read();return{entries:state.audit.slice(-Math.min(100,command.limit||25))};}
  if(op==='file.read')return{file:expose(get(await read(),command.fileId))};
  if(op==='file.history'){const state=await read();const current=state.files.find(f=>f.id===command.fileId);const entries=(state.history||[]).filter(h=>h.fileId===command.fileId);if(!current&&!entries.length)fail('NOT_FOUND','File not found');return{fileId:command.fileId,currentRevision:current?hash(current):null,retention:{versionsPerFile:HISTORY_VERSIONS,maxBytes:HISTORY_BYTES,pruning:'Oldest recorded revisions first; oversized snapshots are not retained'},revisions:entries.slice().reverse().map(({revision,at,origin,snapshot})=>({revision,at,origin,name:snapshot.name,kind:snapshot.kind,updatedAt:snapshot.updatedAt}))};}
  if(op==='spreadsheet.read'){
   const file=get(await read(),command.fileId);const sheet=selectSheet(file,command.sheetId);const parts=(command.range||'A1:J20').split(':');const start=cellAddress(parts[0]),end=cellAddress(parts[1]||parts[0]);if(end.row<start.row||end.col<start.col||(end.row-start.row+1)*(end.col-start.col+1)>10000)fail('INVALID_RANGE','Read up to 10000 cells in a forward rectangle');
   const {formulaInput}=await import('../shared/cells.mjs');const {FormulaEngine}=await import('../shared/formulas.mjs');const engine=FormulaEngine.buildFromSheets(Object.fromEntries(file.data.sheets.map(s=>[s.name,s.cells.map(r=>r.map(formulaInput))])));try{const id=engine.getSheetId(sheet.name);const values=[],raw=[];for(let r=start.row;r<=end.row;r++){const row=[],src=[];for(let c=start.col;c<=end.col;c++){const v=engine.getCellValue({sheet:id,row:r,col:c});row.push(v&&typeof v==='object'?{error:v.value||v.message||String(v)}:v);src.push(sheet.cells[r]?.[c]??'');}values.push(row);raw.push(src);}return{fileId:file.id,revision:hash(file),sheetId:sheet.id,range:command.range||'A1:J20',values,raw};}finally{engine.destroy();}
  }
  if(op==='file.export'){const f=get(await read(),command.fileId);str(command.outputPath,'outputPath',32000);if(!path.isAbsolute(command.outputPath))fail('INVALID_PATH','Export requires an absolute output path');const result=await require('./formats.cjs').exportFile(expose(f),command.format,command.outputPath);return{...result,fileId:f.id,revision:hash(f)};}
  const mutations=['file.create','file.update','file.import','file.restore','document.append','document.replaceText','document.format','spreadsheet.write','spreadsheet.format','spreadsheet.edit','slides.add','notebook.addPage','notebook.updatePage','notebook.deletePage'];if(!mutations.includes(op))fail('UNKNOWN_OPERATION','Unsupported operation: '+op);
  str(command.requestId,'requestId',128);if(!command.requestId)fail('REQUEST_ID_REQUIRED','Use a unique requestId and reuse it only for retries of the same command');const commandHash=hash(command);let imported; if(op==='file.import'){str(command.inputPath,'inputPath',32000);if(!path.isAbsolute(command.inputPath))fail('INVALID_PATH','Import requires an absolute input path');const old=(await read()).receipts.find(r=>r.requestId===command.requestId);if(old){if(old.commandHash!==commandHash)fail('REQUEST_ID_REUSED','requestId was used for another command');return {...old.result,replayed:true};}imported=await require('./formats.cjs').importFile(command.inputPath,command.kind,command.name);}
  return transaction(async state=>{
   const receipt=state.receipts.find(x=>x.requestId===command.requestId);if(receipt){if(receipt.commandHash!==commandHash)fail('REQUEST_ID_REUSED','requestId was already used for a different command');return{noWrite:true,result:{...receipt.result,replayed:true}};}
   let file;let warnings=[];
   if(op==='file.create'||op==='file.import'){
    let kind=command.kind,name=command.name,data=command.data;
    if(op==='file.import'){str(command.inputPath,'inputPath',32000);if(!path.isAbsolute(command.inputPath))fail('INVALID_PATH','Import requires an absolute input path');({kind,name,data,warnings=[]}=imported);}
    if(!kinds.includes(kind))fail('INVALID_KIND','Use document, spreadsheet, presentation, or notebook');str(name,'name',300);if(!name.trim())fail('INVALID_ARGUMENT','File name is required');file={id:crypto.randomUUID(),kind,name,updatedAt:new Date().toISOString(),data:dataValid(kind,data||initialData(kind))};state.files.push(file);
   }else{
    file=get(state,command.fileId);check(file,command.expectedRevision);remember(state,file,'baseline');
    if(op==='file.restore'){const version=(state.history||[]).find(h=>h.fileId===file.id&&h.revision===command.targetRevision);if(!version)fail('NOT_FOUND','Requested revision is no longer retained');file.name=version.snapshot.name;file.data=structuredClone(version.snapshot.data);}
    if(op==='document.replaceText'){
     const node=documentNode(file,command.nodePath||[]),find=str(command.find,'find'),replacement=str(command.replacement,'replacement');if(!find)fail('INVALID_ARGUMENT','find must not be empty');
     let replacements=0,totalBytes=0;const plans=[];const byteDelta=Buffer.byteLength(replacement)-Buffer.byteLength(find);const measure=n=>{if(n.type==='text')totalBytes+=Buffer.byteLength(n.text);(n.content||[]).forEach(measure);};measure(file.data.content);
     const plan=n=>{if(n.type==='text'){let matches=0,offset=0;while((offset=n.text.indexOf(find,offset))!==-1){matches++;offset+=find.length;}const length=n.text.length+matches*(replacement.length-find.length);if(length>1000000)fail('LIMIT_EXCEEDED','Replacement would exceed one million characters in a text node');totalBytes+=matches*byteDelta;replacements+=matches;if(matches)plans.push(n);}(n.content||[]).forEach(plan);};plan(node);
     if(totalBytes>10*1024*1024)fail('LIMIT_EXCEEDED','Replacement would exceed 10 MiB of document text');if(!replacements)fail('NOT_FOUND','No literal match within an individual text node');for(const n of plans)n.text=n.text.split(find).join(replacement);
     const prune=n=>{if(n.content){n.content=n.content.filter(c=>c.type!=='text'||c.text.length>0);n.content.forEach(prune);}};prune(file.data.content);delete file.data.html;
    }
    if(op==='document.format'){
     const node=documentNode(file,command.nodePath);if(command.marks===undefined&&command.alignment===undefined&&command.heading===undefined)fail('INVALID_ARGUMENT','Supply marks, alignment or heading');
     if(command.marks!==undefined){const marks=validateMarks(command.marks);const walk=n=>{if(n.type==='text')n.marks=structuredClone(marks);(n.content||[]).forEach(walk);};walk(node);}
     if(command.alignment!==undefined){if(!['left','center','right','justify'].includes(command.alignment)||!['paragraph','heading'].includes(node.type))fail('INVALID_ARGUMENT','Alignment requires a paragraph or heading and left, center, right or justify');node.attrs={...node.attrs,textAlign:command.alignment};}
     if(command.heading!==undefined){if(!Number.isInteger(command.heading)||command.heading<0||command.heading>6||!['paragraph','heading'].includes(node.type))fail('INVALID_ARGUMENT','heading requires a paragraph or heading and a level from 0 to 6');node.type=command.heading?'heading':'paragraph';node.attrs={...node.attrs};if(command.heading)node.attrs.level=command.heading;else delete node.attrs.level;}delete file.data.html;
    }
    if(op==='spreadsheet.edit'){selectSheet(file,command.sheetId);const {applySpreadsheetCommand}=await import('../shared/spreadsheet-operations.mjs');file.data=applySpreadsheetCommand(file.data,command);}
    if(op==='spreadsheet.format'){selectSheet(file,command.sheetId);const {applyCellFormatting}=await import('../shared/cell-styles.mjs');file.data=applyCellFormatting(file.data,command);}
    if(op==='file.update'){if(command.name!==undefined)file.name=str(command.name,'name',300);if(command.data!==undefined)file.data=dataValid(file.kind,command.data);}
    if(op==='document.append'){if(file.kind!=='document')fail('WRONG_FILE_TYPE','Needs a document');const text=str(command.text,'text');if(file.data.html&&!file.data.content)fail('UNSUPPORTED_CONTENT','Convert this HTML document in the editor before a structured append');const doc=file.data.content||{type:'doc',content:[]};doc.content=[...(doc.content||[]),...text.split(/\r?\n/).map(t=>({type:'paragraph',...(t?{content:[{type:'text',text:t}]}:{})}))];file.data={content:doc};}
    if(op==='spreadsheet.write'){const s=selectSheet(file,command.sheetId);const start=cellAddress(command.start||'A1');const values=command.values;if(!Array.isArray(values)||!values.length||values.length>10000)fail('INVALID_ARGUMENT','values must be a nonempty rectangular array');const width=values[0]?.length;if(!width||values.some(r=>!Array.isArray(r)||r.length!==width)||values.length*width>10000)fail('LIMIT_EXCEEDED','Write a rectangle of at most 10000 cells');if(start.row+values.length>10000||start.col+width>1000)fail('LIMIT_EXCEEDED','Write exceeds worksheet bounds');for(let r=0;r<values.length;r++){while(s.cells.length<=start.row+r)s.cells.push([]);const row=s.cells[start.row+r];while(row.length<start.col)row.push('');values[r].forEach((v,c)=>{if(v!==null&&!['string','number','boolean'].includes(typeof v))fail('INVALID_DATA','Cells require scalar values');row[start.col+c]=v===null?'':String(v);});}s.rows=Math.max(s.rows||40,start.row+values.length);s.cols=Math.max(s.cols||16,start.col+width);}
    if(op==='slides.add'){if(file.kind!=='presentation')fail('WRONG_FILE_TYPE','Needs a presentation');const s=command.slide||{};const slide={id:crypto.randomUUID(),title:str(s.title,'title',20000),body:s.body===undefined?'':str(s.body,'body',50000),right:s.right===undefined?'':str(s.right,'right',50000),notes:s.notes===undefined?'':str(s.notes,'notes',50000),layout:s.layout||'content'};file.data.slides=[...(file.data.slides||[]),slide];}
    if(op==='notebook.addPage'){if(file.kind!=='notebook')fail('WRONG_FILE_TYPE','Needs a notebook');file.data.pages=[...(file.data.pages||[]),{id:crypto.randomUUID(),title:str(command.title,'title',20000),text:str(command.text,'text')}];}
    if(op==='notebook.updatePage'||op==='notebook.deletePage'){if(file.kind!=='notebook')fail('WRONG_FILE_TYPE','Needs a notebook');const pages=file.data.pages||[],page=pages.find(p=>p.id===command.pageId);if(!page)fail('NOT_FOUND','Notebook page not found');if(op==='notebook.deletePage'){if(pages.length<=1)fail('INVALID_DATA','Keep at least one notebook page');file.data.pages=pages.filter(p=>p.id!==command.pageId);}else{if(command.title===undefined&&command.text===undefined)fail('INVALID_ARGUMENT','Supply title or text');if(command.title!==undefined)page.title=str(command.title,'title',20000);if(command.text!==undefined)page.text=str(command.text,'text');}}
    file.updatedAt=new Date().toISOString();dataValid(file.kind,file.data);
   }
   const result={file:expose(file),replayed:false,warnings};if(command.dryRun)return{noWrite:true,result:{...result,dryRun:true}};
   remember(state,file,'agent:'+op);state.receipts.push({requestId:command.requestId,commandHash,result});state.receipts=state.receipts.slice(-128);state.audit.push({operation:op,requestId:command.requestId,fileId:file.id,revision:hash(file),at:new Date().toISOString(),actor:'agent'});state.audit=state.audit.slice(-256);return{result};
  });
 }
 async function snapshot(){const state=await read();return state.files.map(expose);}
 async function saveSnapshot(incoming,baseline){validateFiles(incoming);return transaction(async state=>{
  const base=new Map(baseline.map(f=>[f.id,f])),next=new Map(incoming.map(f=>[f.id,f]));const conflicts=[];
  for(const f of baseline){const n=next.get(f.id);if(!n||hash(n)!==hash(f)){const current=state.files.find(x=>x.id===f.id);if(!current||hash(current)!==hash(f))conflicts.push(f.id);}}
  for(const f of incoming)if(!base.has(f.id)&&state.files.some(x=>x.id===f.id))conflicts.push(f.id);
  if(conflicts.length)fail('REVISION_CONFLICT','Another editor or agent changed this file. Your open edits are preserved. Save a backup before reloading.',{fileIds:conflicts});
  let changed=false;for(const f of baseline)if(!next.has(f.id)){remember(state,get(state,f.id),'human:before-delete');state.files=state.files.filter(x=>x.id!==f.id);changed=true;}
  for(const f of incoming)if(!base.has(f.id)||hash(f)!==hash(base.get(f.id))){const clean=structuredClone(f);delete clean.revision;const i=state.files.findIndex(x=>x.id===f.id);if(i<0)state.files.push(clean);else{remember(state,state.files[i],'baseline');state.files[i]=clean;}remember(state,clean,'human:ui.save');changed=true;}
  if(changed){state.audit.push({operation:'ui.save',actor:'human',at:new Date().toISOString(),fileIds:incoming.filter(f=>!base.has(f.id)||hash(f)!==hash(base.get(f.id))).map(f=>f.id)});state.audit=state.audit.slice(-256);}
  return{noWrite:!changed,result:state.files.map(expose)};
 });}
 return{execute,snapshot,saveSnapshot,workspace:dir};
}
module.exports={createEngine,hash,dataValid,validateFiles};
