'use strict';
const fs=require('node:fs/promises');
const path=require('node:path');
const {createHash,randomUUID}=require('node:crypto');
const kinds=['document','spreadsheet','presentation','notebook'];
function fail(code,message){const e=new Error(message);e.code=code;throw e;}
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function nodeText(n){if(!n)return '';if(n.type==='text')return n.text||'';if(n.type==='hardBreak')return '\n';return (n.content||[]).map(nodeText).join(['doc','bulletList','orderedList','table','tableRow'].includes(n.type)?'\n':'');}
function plainHtml(html){return String(html).replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(p|div|h[1-6]|li|tr)>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;|&#39;/g,"'").replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim();}
function tiptap(text){return {type:'doc',content:String(text).split(/\r?\n/).map(t=>({type:'paragraph',content:t?[{type:'text',text:t}]:[]}))};}
function docText(data,warnings){if(data.content)return nodeText(data.content);if(data.html){warnings.push('HTML converted to plain paragraphs; formatting and embedded media are lost.');return plainHtml(data.html);}return '';}
function csvEncode(rows){return rows.map(r=>r.map(v=>{const s=String(v??'');return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}).join(',')).join('\r\n');}
function csvParse(input){const rows=[];let row=[],field='',quoted=false,closed=false;const s=input.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(c==='"'){if(s[i+1]==='"'){field+='"';i++;}else{quoted=false;closed=true;}}else field+=c;}else if(c===','||c==='\n'||c==='\r'){row.push(field);field='';closed=false;if(c!==','){rows.push(row);row=[];if(c==='\r'&&s[i+1]==='\n')i++;}}else if(c==='"'){if(field||closed)fail('INVALID_INPUT','Invalid CSV quote');quoted=true;}else{if(closed)fail('INVALID_INPUT','Unexpected text after CSV quote');field+=c;}}if(quoted)fail('INVALID_INPUT','Unterminated CSV quote');if(field||row.length||closed)rows.push([...row,field]);return rows;}
function scalar(v){return typeof v==='string'&&v!==''&&/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/.test(v)&&v.replace(/[^0-9]/g,'').length<=15?Number(v):v;}
function validate(file){if(!file||!kinds.includes(file.kind)||!file.data||typeof file.data!=='object')fail('INVALID_INPUT','Expected file kind and data');}
async function exportFile(file,format,outputPath){validate(file);format=String(format).toLowerCase().replace(/^\./,'');const allowed={document:['json','txt','md','html','docx'],spreadsheet:['json','csv','xlsx'],presentation:['json','pptx'],notebook:['json','txt','md']};if(!allowed[file.kind].includes(format))fail('INVALID_FORMAT',`Unsupported ${file.kind} export: ${format}`);const warnings=[];let bytes;
 if(format==='json')bytes=Buffer.from(JSON.stringify({name:file.name,kind:file.kind,data:file.data},null,2));
 else if(file.kind==='document'){
  const semantic=require('./document-format.cjs');const content=file.data.content||semantic.fromHtml(file.data.html||'',warnings);
  if(format==='html')bytes=Buffer.from(semantic.toHtml(content,warnings));
  else if(format==='docx')bytes=await semantic.toDocx(content,warnings);
  else {warnings.push('Plain text and Markdown export retain text only; formatting and media are omitted.');bytes=Buffer.from(nodeText(content));}
 }else if(file.kind==='notebook'){warnings.push('Notebook text export loses page IDs and formatting.');bytes=Buffer.from((file.data.pages||[]).map(p=>(format==='md'?'# ':'')+(p.title||'')+'\n\n'+(p.text||'')).join('\n\n'));}
 else if(file.kind==='spreadsheet'){
  const sheets=file.data.sheets||[];
  if(format==='csv'){const s=sheets.find(s=>s.id===file.data.activeSheet)||sheets[0];warnings.push('CSV exports only the active sheet as raw text; workbook metadata and formatting are lost. Formula strings remain literal CSV fields.');bytes=Buffer.from(csvEncode(s?.cells||[]));}
  else {const ExcelJS=require('exceljs');const book=new ExcelJS.Workbook();let hf;try{const {FormulaEngine}=await import('../shared/formulas.mjs');const {formulaInput}=await import('../shared/cells.mjs');hf=FormulaEngine.buildFromSheets(Object.fromEntries(sheets.map(s=>[s.name,(s.cells||[]).map(r=>r.map(v=>{return formulaInput(v);}))])));}catch{warnings.push('Formula calculation unavailable; workbook consumers must recalculate.');}try{for(const s of sheets){const ws=book.addWorksheet(s.name);(s.cells||[]).forEach((row,ri)=>row.forEach((v,ci)=>{const cell=ws.getCell(ri+1,ci+1);if(typeof v==='string'&&v.startsWith('=')){let result=hf?.getCellValue({sheet:hf.getSheetId(s.name),row:ri,col:ci});if(result&&typeof result==='object'){warnings.push(`Formula cache unavailable at ${s.name}!${cell.address}.`);result=undefined;}cell.value={formula:v.slice(1),...(result==null?{}:{result})};}else cell.value=typeof v==='string'&&v.startsWith("'")?v.slice(1):scalar(v)??null;}));for(const [address,style] of Object.entries(s.styles||{})){if(!/^[A-Z]{1,3}[1-9][0-9]{0,4}$/.test(address))continue;const cell=ws.getCell(address);cell.font={bold:!!style.bold,italic:!!style.italic,...(/^#[a-f0-9]{6}$/i.test(style.color)?{color:{argb:'FF'+style.color.slice(1).toUpperCase()}}:{})};if(style.numberFormat)cell.numFmt=style.numberFormat;if(/^#[a-f0-9]{6}$/i.test(style.fill))cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+style.fill.slice(1).toUpperCase()}};if(['left','center','right'].includes(style.align))cell.alignment={horizontal:style.align};}}book.calcProperties.fullCalcOnLoad=true;bytes=Buffer.from(await book.xlsx.writeBuffer());}finally{hf?.destroy();}warnings.push('XLSX preserves cell values, formulas and basic cell styles; charts, merged cells and advanced workbook features are not represented.');}
 }else if(format==='pptx'){const PptxGenJS=require('pptxgenjs');const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.title=file.name;const colors={editorial:['F5F1E8','222222'],paper:['FFFFFF','222222'],cobalt:['1947E5','FFFFFF'],midnight:['121826','FFFFFF']};const [bg,fg]=colors[file.data.theme]||colors.editorial;for(const item of file.data.slides||[]){const slide=pptx.addSlide();slide.background={color:String(item.background||bg).replace(/^#/,'')};slide.addText(item.title||'',{x:.75,y:.65,w:11.8,h:1.2,fontSize:item.layout==='title'?42:30,bold:true,color:fg,fit:'shrink'});slide.addText(item.body||'',{x:.8,y:2.15,w:item.image||item.layout==='columns'?5.7:11.6,h:3.8,fontSize:22,color:fg,fit:'shrink'});if(item.layout==='columns')slide.addText(item.right||'',{x:7,y:2.15,w:5.5,h:3.8,fontSize:22,color:fg,fit:'shrink'});if(item.image){if(!/^data:image\/(png|jpeg|jpg|gif);base64,/i.test(item.image))fail('INVALID_INPUT','PPTX images must be embedded PNG/JPEG/GIF data URLs');slide.addImage({data:item.image,x:8.1,y:1.8,w:4.3,h:3.6});}if(item.notes)slide.addNotes(item.notes);}bytes=Buffer.from(await pptx.write({outputType:'nodebuffer'}));warnings.push('PPTX preserves slide text, notes and embedded images with approximate layout; animations and exact editor typography are not supported.');}
 try{await fs.writeFile(outputPath,bytes,{flag:'wx'});}catch(e){if(e.code==='EEXIST')fail('OUTPUT_EXISTS','Output already exists; no file was overwritten');throw e;}return {path:path.resolve(outputPath),format,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),warnings:[...new Set(warnings)]};
}

function boundArchive(bytes){
 let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(bytes.readUInt32LE(i)===0x06054b50){end=i;break;}
 if(end<0)fail('INVALID_INPUT','Invalid Office ZIP directory');const count=bytes.readUInt16LE(end+10);let pos=bytes.readUInt32LE(end+16),total=0;
 if(count===65535||count>10000||pos>=bytes.length)fail('LIMIT_EXCEEDED','Archive directory exceeds limits');
 for(let i=0;i<count;i++){if(pos+46>bytes.length||bytes.readUInt32LE(pos)!==0x02014b50)fail('INVALID_INPUT','Invalid ZIP entry');const expanded=bytes.readUInt32LE(pos+24);if(expanded===0xffffffff)fail('LIMIT_EXCEEDED','ZIP64 imports are not supported');total+=expanded;if(total>100*1024*1024)fail('LIMIT_EXCEEDED','Expanded archive exceeds 100 MB');pos+=46+bytes.readUInt16LE(pos+28)+bytes.readUInt16LE(pos+30)+bytes.readUInt16LE(pos+32);}
}
async function importFile(inputPath,kind,name){const format=path.extname(inputPath).slice(1).toLowerCase();const warnings=[];let data,inferred;const stat=await fs.stat(inputPath);if(stat.size>25*1024*1024)fail('LIMIT_EXCEEDED','Input exceeds 25 MB');const bytes=await fs.readFile(inputPath);if(['docx','xlsx'].includes(format))boundArchive(bytes);
 if(format==='json'){let file;try{file=JSON.parse(bytes.toString('utf8'));}catch{fail('INVALID_INPUT','Invalid JSON');}validate(file);if(kind&&kind!==file.kind)fail('INVALID_INPUT','Requested kind does not match JSON kind');return {name:name||file.name||path.basename(inputPath,'.json'),kind:file.kind,data:file.data,warnings};}
 if(['txt','md','html','docx'].includes(format)){inferred=kind==='notebook'?'notebook':'document';let text;let content;if(format==='docx'){const result=await require('mammoth').convertToHtml({buffer:bytes},{styleMap:["u => u"]});warnings.push(...result.messages.map(m=>m.message),'DOCX import preserves semantic content; exact page layout and advanced styles are not retained.');content=require('./document-format.cjs').fromHtml(result.value,warnings);text=nodeText(content);}else if(format==='html'){content=require('./document-format.cjs').fromHtml(bytes.toString('utf8'),warnings);text=nodeText(content);warnings.push('HTML is rebuilt from safe semantic content; CSS, scripts, events and external media are omitted.');}else {text=bytes.toString('utf8');if(format==='md')warnings.push('Markdown imported as literal text; markup is not interpreted.');}data=inferred==='notebook'?{pages:[{id:randomUUID(),title:name||path.basename(inputPath),text}]}:{content:content||tiptap(text)};
 }else if(format==='csv'||format==='xlsx'){inferred='spreadsheet';let sheets;if(format==='csv')sheets=[{id:randomUUID(),name:'Sheet1',cells:csvParse(bytes.toString('utf8'))}];else {const ExcelJS=require('exceljs');const book=new ExcelJS.Workbook();await book.xlsx.load(bytes);sheets=book.worksheets.map(ws=>{if(ws.rowCount>10000||ws.columnCount>1000||ws.rowCount*ws.columnCount>1000000)fail('LIMIT_EXCEEDED','Worksheet dimensions exceed import limits');const cells=[],styles={};for(let r=1;r<=ws.rowCount;r++){const row=[];for(let c=1;c<=ws.columnCount;c++){const cell=ws.getCell(r,c);const style={};if(cell.font?.bold)style.bold=true;if(cell.font?.italic)style.italic=true;if(cell.numFmt&&cell.numFmt!=='General')style.numberFormat=cell.numFmt;if(cell.font?.color?.argb)style.color='#'+cell.font.color.argb.slice(-6);if(cell.fill?.type==='pattern'&&cell.fill.fgColor?.argb)style.fill='#'+cell.fill.fgColor.argb.slice(-6);if(['left','center','right'].includes(cell.alignment?.horizontal))style.align=cell.alignment.horizontal;if(Object.keys(style).length)styles[cell.address]=style;let v=cell.value;if(cell.formula)v='='+cell.formula;else if(v instanceof Date){v=v.toISOString();warnings.push('Dates imported as ISO text.');}else if(v&&typeof v==='object'){v=v.richText?v.richText.map(t=>t.text).join(''):v.text??v.error??String(v.result??'');warnings.push('Rich or special cell values reduced to text.');}row.push(v==null?'':String(v));}cells.push(row);}return {id:randomUUID(),name:ws.name,cells,styles};});warnings.push('XLSX import retains cell values/formulas and basic cell styles; charts, merges, macros and advanced workbook features are omitted.');}data={sheets,activeSheet:sheets[0]?.id};
 }else fail('INVALID_FORMAT',`Unsupported import format: ${format}`);
 if(kind&&kind!==inferred)fail('INVALID_INPUT',`Cannot import ${format} as ${kind}`);return {name:name||path.basename(inputPath,path.extname(inputPath)),kind:inferred,data,warnings:[...new Set(warnings)]};
}
module.exports={exportFile,importFile};
