import Workspace from './Workspace';
import NotebookEditor from './editors/NotebookEditor';
import HistoryPanel from './HistoryPanel';
import SearchPalette from './SearchPalette';
import AutomationPanel from './AutomationPanel';
import {useEffect,useRef,useState} from 'react';
import {FileText,Table2,Presentation,BookOpen,Search,Plus,FolderOpen,Star,ArrowLeft,MoreHorizontal,LayoutGrid,List,HardDrive,ArrowUpRight,Download,Upload,Copy,Trash2,Check,PanelLeftClose,Clock3} from 'lucide-react';
import DocumentEditor from './editors/DocumentEditor';import SpreadsheetEditor from './editors/SpreadsheetEditor';import PresentationEditor from './editors/PresentationEditor';import type{OfficeFile,FileKind}from'./types';import{downloadFile}from'./io';
const apps=[{kind:'document',label:'Documents',singular:'Document',verb:'Start writing',icon:FileText,color:'blue'},{kind:'spreadsheet',label:'Spreadsheets',singular:'Spreadsheet',verb:'Make the numbers work',icon:Table2,color:'green'},{kind:'presentation',label:'Presentations',singular:'Presentation',verb:'Bring your ideas to life',icon:Presentation,color:'orange'},{kind:'notebook',label:'Notebooks',singular:'Notebook',verb:'Keep your thoughts together',icon:BookOpen,color:'purple'}]as const;
const makeFile=(kind:FileKind,name?:string,data?:any):OfficeFile=>({id:crypto.randomUUID(),name:name||`Untitled ${apps.find(a=>a.kind===kind)?.singular.toLowerCase()}`,kind,updatedAt:new Date().toISOString(),data:data||(kind==='notebook'?{pages:[{id:crypto.randomUUID(),title:'Untitled page',text:''}]}:{})});

export default function App(){
 const[historyOpen,setHistoryOpen]=useState(false);const historyRef=useRef(false);historyRef.current=historyOpen;
 const[palette,setPalette]=useState(false);const[conflict,setConflict]=useState(false);const[automation,setAutomation]=useState(false);const baseline=useRef<OfficeFile[]>([]);const persisted=useRef('[]');const writes=useRef(Promise.resolve(true));const saving=useRef(false);const[files,setFiles]=useState<OfficeFile[]>([]);const[ready,setReady]=useState(false);const[error,setError]=useState('');const[active,setActive]=useState<string|null>(null);const[filter,setFilter]=useState('all');const[search,setSearch]=useState('');const[grid,setGrid]=useState(false);const[menu,setMenu]=useState<string|null>(null);const[saved,setSaved]=useState('Opening workspace');const[undoDelete,setUndoDelete]=useState<OfficeFile|null>(null);const[help,setHelp]=useState(false);const latest=useRef(files);const readyRef=useRef(false);const backupInput=useRef<HTMLInputElement>(null);const first=useRef(true);const saveSeq=useRef(0);
 const persist=(value:OfficeFile[])=>{const job=writes.current.then(async()=>{saving.current=true;const seq=++saveSeq.current;setSaved('Saving');try{if(window.office){const r=await window.office.save(value,baseline.current);if(!r.ok){setConflict(r.code==='REVISION_CONFLICT');throw Error(r.error);}setConflict(false);baseline.current=structuredClone(value);}else localStorage.setItem('office-workspace-preview',JSON.stringify(value));if(seq===saveSeq.current)setSaved(window.office?'Saved on this device':'Saved in this browser');persisted.current=JSON.stringify(value);return true;}catch(e:any){setError(e.message);setSaved('Save failed');return false;}finally{saving.current=false;}});writes.current=job;return job;};
 useEffect(()=>{(async()=>{try{const data=window.office?await window.office.load():JSON.parse(localStorage.getItem('office-workspace-preview')||'[]');baseline.current=data;persisted.current=JSON.stringify(data);setFiles(data);latest.current=data;setReady(true);readyRef.current=true;setSaved(window.office?'Saved on this device':'Browser preview');}catch(e:any){setError(e.message);}})();},[]);
 useEffect(()=>{latest.current=files;if(!ready)return;if(first.current){first.current=false;return;}setSaved('Saving');const t=setTimeout(()=>persist(files),200);return()=>clearTimeout(t);},[files,ready]);
 useEffect(()=>{const flush=()=>{if(readyRef.current)persist(latest.current);};const close=async()=>{if(!readyRef.current){await window.office?.finishClose();return;}if(await persist(latest.current))await window.office?.finishClose();};const key=(e:KeyboardEvent)=>{if(historyRef.current)return;if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();flush();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(true);}if(e.key==='Escape'){setMenu(null);setHelp(false);setPalette(false);}};window.addEventListener('keydown',key);window.addEventListener('office-closing',close);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('office-closing',close);};},[]);
 useEffect(()=>{if(!window.office)return;const timer=setInterval(async()=>{if(!readyRef.current||saving.current||persisted.current!==JSON.stringify(latest.current))return;const before=JSON.stringify(latest.current);try{const data=await window.office!.load();if(saving.current||before!==JSON.stringify(latest.current)||before===JSON.stringify(data))return;baseline.current=data;persisted.current=JSON.stringify(data);first.current=true;latest.current=data;setFiles(data);}catch(e:any){setError(e.message);}},1500);return()=>clearInterval(timer);},[]);
 const current=files.find(f=>f.id===active);const update=(data:any)=>setFiles(prev=>prev.map(f=>f.id===active?{...f,data,updatedAt:new Date().toISOString()}:f));
 const create=(kind:FileKind,name?:string,data?:any)=>{if(!ready)return;const f=makeFile(kind,name,data);setFiles(prev=>[f,...prev]);setActive(f.id);};
 const visible=files.filter(f=>(filter==='all'||filter==='starred'&&f.starred||filter===f.kind)&&f.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
 async function importBackup(file:File){try{if(file.size>25*1024*1024)throw Error('Backup exceeds 25 MB.');const incoming=JSON.parse(await file.text());if(!Array.isArray(incoming)||incoming.some(f=>!f||!apps.some(a=>a.kind===f.kind)||typeof f.name!=='string'||!f.data))throw Error('Choose an Office Workspace backup JSON file.');const prepared=incoming.map(f=>({...f,id:crypto.randomUUID(),updatedAt:new Date().toISOString()}));if(!window.office)throw Error('Use the desktop app to validate and import workspace backups.');const checked=await window.office.validate(prepared);if(!checked.ok)throw Error(checked.error);setFiles(prev=>[...prepared,...prev]);}catch(e:any){setError(e.message);}}
 async function keepCopies(){await writes.current;if(!window.office)return;const open=latest.current;const clean=(f:OfficeFile)=>JSON.stringify({...f,revision:undefined});const dirty=open.filter(f=>{const b=baseline.current.find(x=>x.id===f.id);return !b||clean(f)!==clean(b);});const remote=await window.office.load();const copies=dirty.map(f=>({...makeFile(f.kind,f.name+' (recovered copy)',structuredClone(f.data)),starred:f.starred}));baseline.current=remote;persisted.current=JSON.stringify(remote);setConflict(false);setError('');setFiles([...remote,...copies]);const i=dirty.findIndex(f=>f.id===active);if(i>=0)setActive(copies[i].id);}
 function openHistory(){if(window.office)setHistoryOpen(true);}
 async function restored(){const before=JSON.stringify(latest.current);await writes.current;const data=await window.office!.load();if(before!==JSON.stringify(latest.current))throw Error('Your workspace changed while restoring. Close history to review the latest edits.');baseline.current=data;persisted.current=JSON.stringify(data);first.current=true;latest.current=data;setFiles(data);setSaved('Restored and saved on this device');}
 return <div className="office-app">{historyOpen&&current&&<HistoryPanel prepare={()=>persist(latest.current)} file={current} onClose={()=>setHistoryOpen(false)} onRestored={restored}/>}

  {!current&&<aside className="sidebar"><div className="workspace-name"><div className="workspace-mark"><LayoutGrid size={22}/></div><span>Workspace<small>YOUR PERSONAL OFFICE</small></span></div><button className="new-button" onClick={()=>create('document')} disabled={!ready}><Plus size={18}/>Create new</button><div className="nav-label">WORKSPACE</div><nav><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}><LayoutGrid size={18}/>All files<span>{files.length}</span></button><button className={filter==='starred'?'active':''} onClick={()=>setFilter('starred')}><Star size={18}/>Favorites</button></nav><div className="nav-label apps-label">YOUR APPS</div><nav>{apps.map(a=><button key={a.kind} className={filter===a.kind?'active':''} onClick={()=>setFilter(a.kind)}><a.icon size={18} className={a.color}/>{a.label}</button>)}</nav><div className="sidebar-bottom"><div className="local-badge"><HardDrive size={19}/><div>Private by default.<small>Your files stay on this device</small></div></div><button onClick={()=>window.office?window.office.openWorkspace():setHelp(true)}><FolderOpen size={18}/>Open workspace folder</button><button onClick={()=>setHelp(true)}><BookOpen size={18}/>Help & keyboard shortcuts</button><button onClick={()=>setPalette(true)}><Search size={18}/>Search content <kbd>Ctrl K</kbd></button><button onClick={()=>setAutomation(true)}><HardDrive size={18}/>Agent tools</button><div className="account"><div className="avatar">ME</div><div>Personal workspace<small>No account needed</small></div></div></div></aside>}
  {current&&<aside className="workspace-rail" aria-label="Workspace navigation"><button className="rail-brand" aria-label="Workspace home" onClick={()=>setActive(null)}><LayoutGrid size={23}/></button><div className="rail-apps">{apps.map(a=><button key={a.kind} title={a.label} aria-label={'Open '+a.label.toLowerCase()} className={a.kind===current.kind?'active':''} onClick={()=>{setFilter(a.kind);setActive(null);}}><a.icon size={22}/></button>)}</div><div className="rail-bottom"><button aria-label="Search workspace content" title="Search · Ctrl+K" onClick={()=>setPalette(true)}><Search size={20}/></button><button aria-label="Agent tools" title="Agent tools" onClick={()=>setAutomation(true)}><HardDrive size={20}/></button></div></aside>}
  <main inert={historyOpen} className={current?'editor-shell':'main-shell'}>
   {current?<><header className="editor-header"><button className="icon-button" aria-label="Back to workspace" onClick={()=>setActive(null)}><ArrowLeft size={20}/></button><div className={`file-icon ${apps.find(a=>a.kind===current.kind)?.color}`}>{(()=>{const I=apps.find(a=>a.kind===current.kind)!.icon;return<I size={23}/>;})()}</div><input aria-label="File name" value={current.name} onChange={e=>setFiles(prev=>prev.map(f=>f.id===active?{...f,name:e.target.value,updatedAt:new Date().toISOString()}:f))}/><select className="file-switcher" aria-label="Switch file" value="" onChange={e=>setActive(e.target.value)}><option value="" disabled>Switch file</option>{files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button className="subtle history-trigger" onClick={()=>void openHistory()}><Clock3 size={16}/>Version history</button><span className={'save-state '+(saved==='Saving'?'is-saving':saved==='Save failed'?'is-error':'')} role="status" aria-live="polite"><i/>{saved}</span><button className="icon-button" aria-label="Favorite file" onClick={()=>setFiles(prev=>prev.map(f=>f.id===active?{...f,starred:!f.starred}:f))}><Star size={19} fill={current.starred?'#d6a32a':'none'}/></button></header>{error&&<div role="alert" className="error-banner">{error}<button onClick={()=>downloadFile('unsaved-workspace',JSON.stringify(files,null,2),'json').catch(e=>setError(e.message))}>Back up open edits</button>{conflict&&<button onClick={()=>keepCopies().catch(e=>setError(e.message))}>Keep my edits as copies</button>}<button onClick={()=>setError('')}>Dismiss</button></div>}<div className="editor-content" key={current.id}>{current.kind==='document'?<DocumentEditor file={current} onChange={update}/>:current.kind==='spreadsheet'?<SpreadsheetEditor file={current} onChange={update}/>:current.kind==='presentation'?<PresentationEditor file={current} onChange={update}/>:<NotebookEditor file={current} onChange={update}/>}</div></>:
   <Workspace files={files} ready={ready} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} onCreate={create} onOpen={setActive} onFavorite={id=>setFiles(prev=>prev.map(f=>f.id===id?{...f,starred:!f.starred}:f))} onDuplicate={f=>setFiles(prev=>[makeFile(f.kind,f.name+' (copy)',structuredClone(f.data)),...prev])} onRemove={f=>{setUndoDelete(f);setFiles(prev=>prev.filter(x=>x.id!==f.id));}} onImport={()=>backupInput.current?.click()} onExport={()=>downloadFile('workspace-backup',JSON.stringify(files,null,2),'json').catch(e=>setError(e.message))} onSearch={()=>setPalette(true)} onAgents={()=>setAutomation(true)} banner={error&&<div role="alert" className="error-banner">{error}<button onClick={()=>downloadFile('unsaved-workspace',JSON.stringify(files,null,2),'json')}>Back up open edits</button>{conflict&&<button onClick={()=>keepCopies().catch(e=>setError(e.message))}>Keep my edits as copies</button>}<button onClick={()=>setError('')}>Dismiss</button></div>}/>}

  </main><input ref={backupInput} type="file" accept=".json" hidden onChange={e=>{if(e.target.files?.[0])importBackup(e.target.files[0]);e.target.value='';}}/>
  {undoDelete&&<div className="toast">File removed<button onClick={()=>{setFiles(prev=>[undoDelete,...prev]);setUndoDelete(null);}}>Undo</button><button aria-label="Dismiss" onClick={()=>setUndoDelete(null)}>×</button></div>}
  {palette&&<SearchPalette onClose={()=>setPalette(false)} onOpen={id=>{setActive(id);setPalette(false);}}/>} {automation&&<AutomationPanel onClose={()=>setAutomation(false)}/>} {help&&<div className="modal-overlay" onClick={()=>setHelp(false)}><div role="dialog" aria-label="Workspace help" className="help-modal" onClick={e=>e.stopPropagation()}><h2>Your offline workspace</h2><p>Documents, spreadsheets, presentations, and notebooks save automatically on this device. Export files from each editor to use them in other apps.</p><dl><dt>Save now</dt><dd>Ctrl + S</dd><dt>Undo / redo</dt><dd>Ctrl + Z / Ctrl + Y</dd><dt>Copy / paste</dt><dd>Ctrl + C / Ctrl + V</dd><dt>Exit presentation</dt><dd>Esc</dd></dl><p>Export a workspace backup to keep an extra copy. Imported backups are added as new files. Office imports preserve supported content; complex formatting and macros aren’t supported in this version.</p><button className="new-button" onClick={()=>setHelp(false)}>Got it</button></div></div>}
 </div>;
}
