import {useEffect,useState} from 'react';
import {Terminal,Copy,Check,X,FolderOpen,FileText,History,Search} from 'lucide-react';
import {useDialogFocus} from './SearchPalette';
import './Panels.css';
export default function AutomationPanel({onClose}:{onClose:()=>void}){
 const[info,setInfo]=useState<any>(null),[audit,setAudit]=useState<any[]>([]),[copied,setCopied]=useState(false),[error,setError]=useState('');const panel=useDialogFocus(onClose);
 useEffect(()=>{let stopped=false;if(!window.office){setError('Agent tools are available in the Windows desktop app.');return;}Promise.all([window.office.agentInfo(),window.office.audit()]).then(([i,a])=>{if(!stopped){setInfo(i);setAudit(a.entries);}}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;};},[]);
 const configuration=info?JSON.stringify({mcpServers:{office:info.mcp}},null,2):'';
 async function copy(){try{if(window.office)await window.office.copyAgentConfig();else await navigator.clipboard.writeText(configuration);setCopied(true);}catch{setError('Copy failed. Expand the configuration below and copy the text manually.');}}
 return <div className="modal-overlay folio-panel-overlay" onClick={onClose}><section ref={panel} tabIndex={-1} className="help-modal automation-modal folio-panel" role="dialog" aria-modal="true" aria-labelledby="agent-heading" onClick={e=>e.stopPropagation()}><button className="automation-close" aria-label="Close agent tools" onClick={onClose}><X size={20}/></button><div className="panel-eyebrow"><Terminal size={17}/> AGENT WORKSPACE</div><h2 id="agent-heading">Your files. A helping hand.</h2><p>Connect your AI assistant to the same workspace you use here. Read, edit and find files together.</p><div className="automation-facts"><span>Local files</span><span>Shared saved changes</span><span>Version history</span></div>{error&&<p className="panel-error" role="alert">{error}</p>}{!info&&!error&&<p role="status">Loading your workspace connection…</p>}{info&&<><section className="agent-step"><span className="step-number">1</span><div><h3>Start with your workspace</h3><p>Your agent can work with files in this folder.</p><div className="workspace-path"><FolderOpen size={18}/><code>{info.workspace}</code></div></div></section><section className="agent-step"><span className="step-number">2</span><div><h3>Connect your assistant</h3><p>Copy this MCP server entry into your assistant’s MCP configuration, then reconnect the assistant.</p><button className="panel-primary" onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Configuration copied':'Copy MCP configuration'}</button><span className="copy-status" role="status">{copied?'Ready to paste into your assistant.':''}</span><details><summary>View connection configuration</summary><pre>{configuration}</pre></details></div></section><section className="agent-step"><span className="step-number">3</span><div><h3>Give it a useful first task</h3><p className="agent-example">“Find the project plan and summarize its next steps.”</p><div className="capability-grid"><div><Search size={18}/><strong>Find & read</strong><p>Search saved content and inspect file details.</p></div><div><FileText size={18}/><strong>Create & edit</strong><p>Work on documents, sheets, slides and notes.</p></div><div><History size={18}/><strong>Track changes</strong><p>Saved changes appear here with version history.</p></div></div><p className="agent-scope">Connecting grants your assistant local tool access. Your assistant’s own network and model settings still apply.</p></div></section><details className="recent-agent-changes"><summary>Recent workspace changes</summary><div className="automation-audit">{audit.length?audit.slice().reverse().slice(0,6).map((e,i)=><div key={i}><span>{e.actor==='human'?'You':'Agent'}</span><strong>{String(e.operation).replaceAll('.',' · ')}</strong><time dateTime={e.at}>{new Date(e.at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div>):<p>Your first saved edit will appear here.</p>}</div></details></>}</section></div>;
}
