import {useEffect,useState} from 'react';
import {History,X,RotateCcw,Check} from 'lucide-react';
import type {OfficeFile} from './types';
import {useDialogFocus} from './SearchPalette';
import './Panels.css';
export default function HistoryPanel({file,onClose,onRestored,prepare}:{file:OfficeFile,onClose:()=>void,onRestored:()=>Promise<void>,prepare:()=>Promise<boolean>}){
 const[rows,setRows]=useState<any[]>([]),[current,setCurrent]=useState(''),[status,setStatus]=useState('Saving current edits and loading versions…'),[busy,setBusy]=useState(true),[error,setError]=useState(false),[selected,setSelected]=useState('');const panel=useDialogFocus(onClose,busy);
 useEffect(()=>{let stopped=false;prepare().then(ok=>{if(!ok)throw Error('Save your current edits before opening history.');if(!window.office)throw Error('Version history requires the desktop app.');return window.office.command({operation:'file.history',fileId:file.id});}).then(r=>{if(!stopped){setRows(r.revisions);setCurrent(r.currentRevision);setStatus(r.revisions.length?`${r.revisions.length} saved versions`:'No saved versions yet.');}}).catch(e=>{if(!stopped){setError(true);setStatus(e.message);}}).finally(()=>{if(!stopped)setBusy(false);});return()=>{stopped=true;};},[file.id]);
 async function restore(revision:string){if(busy||revision===current)return;setBusy(true);setError(false);setStatus('Restoring your selected version…');try{await window.office!.command({operation:'file.restore',fileId:file.id,targetRevision:revision,expectedRevision:current,requestId:crypto.randomUUID()});await onRestored();onClose();}catch(e:any){setError(true);setStatus(e.message);}finally{setBusy(false);}}
 return <div className="modal-overlay folio-panel-overlay" onClick={()=>{if(!busy)onClose();}}><section ref={panel} tabIndex={-1} className="history-panel folio-panel" role="dialog" aria-modal="true" aria-labelledby="history-heading" aria-busy={busy} onClick={e=>e.stopPropagation()}><header><History size={24}/><div><h2 id="history-heading">Version history</h2><p>{file.name}</p></div><button aria-label="Close history" disabled={busy} onClick={onClose}><X size={20}/></button></header><p className={`history-status ${error?'panel-error':''}`} role={error?'alert':'status'}>{status}</p><div className="history-rows">{rows.map(r=><article className={selected===r.revision?'revision-selected':''} key={r.revision}><div><strong>{new Date(r.at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}<time> · {new Date(r.at).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</time></strong><span>{r.origin?.startsWith('agent:')?'Agent edit':r.origin?.startsWith('human:')?'Your edit':'Saved version'} · {r.name}</span></div>{r.revision===current?<span className="revision-current"><Check size={14}/>Current</span>:<button aria-pressed={selected===r.revision} disabled={busy} onClick={()=>setSelected(r.revision)}>{selected===r.revision?<Check size={15}/>:<RotateCcw size={15}/>} {selected===r.revision?'Selected':'Choose'}</button>}</article>)}</div>{!busy&&!error&&!rows.length&&<div className="panel-empty"><History size={30}/><strong>Your work has a timeline.</strong><p>Saved versions will appear as you make changes.</p></div>}{selected&&<div className="restore-confirmation"><p>Restore the selected version as a new saved change?</p><button className="panel-primary" disabled={busy} onClick={()=>restore(selected)}><RotateCcw size={16}/>{busy?'Restoring…':'Restore selected version'}</button></div>}<footer><span>Restoring creates a new change, so you can return to this version.</span><small>Up to 30 versions per file · 20 MB shared history</small></footer></section></div>;
}
