import {useEffect,useRef,useState} from 'react';
import {Search,FileText,Table2,Presentation,NotebookPen,X} from 'lucide-react';
import './Panels.css';
export function useDialogFocus(onClose:()=>void,blocked=false){
 const panel=useRef<HTMLElement>(null),close=useRef(onClose),busy=useRef(blocked);close.current=onClose;busy.current=blocked;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,node=panel.current;if(!node)return;const items=()=>Array.from(node.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href],summary,[tabindex="0"]')).filter(e=>e.getClientRects().length&&e.tabIndex>=0&&!(e as HTMLButtonElement).disabled);(items()[0]||node).focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!busy.current)close.current();}if(e.key==='Tab'){const all=items(),first=all[0],last=all[all.length-1];if(!first){e.preventDefault();node.focus();}else if(!all.includes(document.activeElement as HTMLElement)){e.preventDefault();(e.shiftKey?last:first).focus();}else if(e.shiftKey&&(document.activeElement===first||document.activeElement===node)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};node.addEventListener('keydown',keys);return()=>{node.removeEventListener('keydown',keys);if(previous?.isConnected)previous.focus();};},[]);return panel;
}
const icons={document:FileText,spreadsheet:Table2,presentation:Presentation,notebook:NotebookPen};
export default function SearchPalette({onClose,onOpen}:{onClose:()=>void,onOpen:(id:string)=>void}){
 const[q,setQ]=useState(''),[results,setResults]=useState<any[]>([]),[selected,setSelected]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');const panel=useDialogFocus(onClose);
 useEffect(()=>{let cancelled=false;setResults([]);setSelected(0);setError('');setLoading(!!q.trim());if(!q.trim())return;const timer=setTimeout(async()=>{try{if(!window.office)throw Error('Open the desktop app to search your saved content.');const r=await window.office.search(q);if(!cancelled)setResults(r.matches);}catch(e:any){if(!cancelled)setError(e.message);}finally{if(!cancelled)setLoading(false);}},180);return()=>{cancelled=true;clearTimeout(timer);};},[q]);
 useEffect(()=>{panel.current?.querySelector(`[data-result="${selected}"]`)?.scrollIntoView({block:'nearest'});},[selected]);
 const status=error||(!q.trim()?'Search across every saved file.':loading?'Searching your workspace…':results.length?`${results.length} matching passages`:'No matching passages');
 return <div className="modal-overlay folio-panel-overlay" onClick={onClose}><section ref={panel} tabIndex={-1} className="search-palette folio-panel" role="dialog" aria-modal="true" aria-label="Search workspace content" onClick={e=>e.stopPropagation()}><div className="palette-input"><Search size={22}/><input aria-label="Search content" role="combobox" aria-expanded={results.length>0} aria-controls="content-search-results" aria-autocomplete="list" aria-activedescendant={results[selected]?`search-result-${selected}`:undefined} placeholder="Search your workspace" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setSelected(i=>results.length?Math.max(0,Math.min(results.length-1,i+(e.key==='ArrowDown'?1:-1))):0);}if(e.key==='Enter'&&results[selected]){e.preventDefault();onOpen(results[selected].fileId);}}}/><button aria-label="Close search" onClick={onClose}><X size={20}/></button></div><div className="palette-status" role="status">{status}</div><div className="palette-results" id="content-search-results" role="listbox" aria-label="Search results" aria-busy={loading}>{results.map((r,i)=>{const Icon=icons[r.kind as keyof typeof icons]||FileText;return <button role="option" aria-selected={i===selected} id={`search-result-${i}`} data-result={i} tabIndex={-1} key={`${r.fileId}-${i}`} className={i===selected?'chosen':''} onMouseMove={()=>setSelected(i)} onClick={()=>onOpen(r.fileId)}><span className={`search-kind ${r.kind}`}><Icon size={21}/></span><span className="search-copy"><strong>{r.name}</strong><small>{r.snippet||'Open this file to view the matching content.'}</small></span><em>{r.kind}</em></button>;})}</div>{!results.length&&!loading&&<div className="panel-empty"><Search size={28}/><strong>{q.trim()?'Try a different word or phrase':'A thought, a figure, a sentence.'}</strong><p>{q.trim()?'Search checks saved content. Try fewer words.':'Find content in documents, spreadsheets, presentations and notebooks.'}</p></div>}<footer><span>↑ ↓ Navigate</span><span>Enter Open</span><span>Esc Close</span></footer></section></div>;
}
